/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.auxiliary;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import java.awt.event.MouseEvent;

/**
 *
 * @author USER
 */
public class RequestStatusPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestStatusPanel
     */
    public RequestStatusPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestIDComboBox = new javax.swing.JComboBox<>();
        searchTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        sortByComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        orderComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestStatusTbl = new javax.swing.JTable();
        deptNameLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(5, 10, 36));
        setPreferredSize(new java.awt.Dimension(793, 428));

        requestIDComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        searchTxtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");

        sortByComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        sortByComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Name", "Status" }));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Sort By");

        orderComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order");

        requestStatusTbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        requestStatusTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestStatusTbl);

        deptNameLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        deptNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        deptNameLbl.setText("Department's Request Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(requestIDComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
                    .addComponent(deptNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(deptNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(requestIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(sortByComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    private User loginUser;
    private String department;
    private RequestManager requestManager;
    private Map<String, List<Request>> requestsMap;
    private String requestFilePath;
    private List<Request> displayedRequests = new ArrayList<>();
    private TransactionType type;

    public RequestStatusPanel(User loginUser, String department, String filePath, JPanel panel, TransactionType type) throws IOException
    {
        initComponents();

        this.loginUser = loginUser;
        this.department = department;
        this.requestFilePath = filePath;
        this.type = type;

        panel.setLayout(new BorderLayout());
        panel.add(this, BorderLayout.CENTER);
        
        deptNameLbl.setText(loginUser.getDepartment() + " Request Status");

        initRequestMode(panel);
        requestStatusTbl.repaint();
    }

    public String getFilePath()
    {
        return this.requestFilePath;
    }

    private void initRequestMode(JPanel panel) throws IOException {
        // TODO Auto-generated method stub
        requestManager = new RequestManager();
        requestsMap = requestManager.loadAllRequests(requestFilePath);

        for(String requestId : requestsMap.keySet())
        {
            requestIDComboBox.addItem(requestId);
        }

        if(!requestsMap.isEmpty())
        {
            String latestId = getLatestRequestID();
            requestIDComboBox.setSelectedItem(latestId);
            loadRequestOnTable(latestId);
        }

        requestIDComboBox.addActionListener(e ->
            {
                String selected = requestIDComboBox.getSelectedItem().toString();
                loadRequestOnTable(selected);
            }
        );

        searching(requestsMap, panel);

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(requestStatusTbl.getModel());
        requestStatusTbl.setRowSorter(sorter);

        sortByComboBox.addActionListener(e -> applySorting());
        orderComboBox.addActionListener(e -> applySorting());
        
        approveOrReject(loginUser, panel);
    }

    private void loadRequestOnTable(String requestId)
    {
        List<Request> list = requestsMap.get(requestId);
        if(list == null) return;

        DefaultTableModel model = (DefaultTableModel) requestStatusTbl.getModel();
        model.setRowCount(0);

        displayedRequests.clear();
        for (Request req : list) {
            displayedRequests.add(req);
            model.addRow(new Object[] {
                req.getItemCode(), req.getItemName(), req.getQuantity(), req.getUnit(), req.getStatus()
            });
        }

        requestStatusTbl.setFillsViewportHeight(true);
        requestStatusTbl.setRowHeight(24);

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                        boolean isSelected, boolean hasFocus,
                                                        int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                setHorizontalAlignment(JLabel.CENTER);
                
                if (!isSelected) {
                    c.setBackground(row % 2 == 1 ? new Color(245,245, 245) : Color.WHITE);
                }

                return c;
            }
        };

        for (int i = 0; i < requestStatusTbl.getColumnCount(); i++) {
            requestStatusTbl.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    private String getLatestRequestID() 
    {
        return requestsMap.keySet().stream()
                .sorted()
                .reduce((first, second) -> second)
                .orElse(null);
    }

    private void searching(Map<String, List<Request>> requestMap, JPanel panel)
    {
        JPopupMenu popup = new JPopupMenu();
        popup.setFocusable(true);

        JList<String> suggestionList = new JList<>();
        JScrollPane scrollPane = new JScrollPane(suggestionList);

        scrollPane.setPreferredSize(new Dimension(Math.max(searchTxtField.getPreferredSize().width, 200), 100));
        popup.add(scrollPane);

        popup.setInvoker(searchTxtField);

        searchTxtField.getDocument().addDocumentListener(new DocumentListener() {
            public void update()
            {
                Object selectedObj = requestIDComboBox.getSelectedItem();
                if(selectedObj == null) return;
                String selectedReqObj = selectedObj.toString();

                List<Request> requestItems = requestMap.get(selectedReqObj);
                if(requestItems == null) return;

                String text = searchTxtField.getText().toLowerCase();
                if(text.isEmpty())
                {
                    popup.setVisible(false);
                    return;
                }

                DefaultListModel<String> model = new DefaultListModel<>();

                for (Request req : requestItems) {
                    if (req.getItemName().toLowerCase().contains(text) && !text.isEmpty()) {
                        model.addElement(req.getItemName() + "(" + req.getRequestId() + ")");
                    }
                }
                suggestionList.setModel(model);

                if (!model.isEmpty()) {
                    // update popup width to match the text field before showing
                    int width = Math.max(searchTxtField.getWidth(), searchTxtField.getPreferredSize().width);
                    if (width <= 0) width = Math.max(searchTxtField.getPreferredSize().width, 200);
                    scrollPane.setPreferredSize(new Dimension(width, 100));
                    suggestionList.revalidate();
                    suggestionList.repaint();

                    if(!popup.isVisible()) {
                        SwingUtilities.invokeLater(() -> {
                            popup.show(searchTxtField, 0, searchTxtField.getHeight());
                            // keep typing in the search field even when popup is visible
                            searchTxtField.requestFocusInWindow();
                        });
                    }
                    popup.revalidate();
                    popup.repaint();
                } else {
                    popup.setVisible(false);
                }
            }
            @Override
            public void insertUpdate(DocumentEvent e) { update(); }
            @Override
            public void removeUpdate(DocumentEvent e) { update(); }
            @Override
            public void changedUpdate(DocumentEvent e) { update(); }
        });

        suggestionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String selected = suggestionList.getSelectedValue();
                if (selected != null) {
                    String selectedName = selected.split("\\(")[0].trim();

                    String selectedReqID = requestIDComboBox.getSelectedItem().toString();
                    List<Request> requestItems = requestMap.get(selectedReqID);
                    if(requestItems == null) return;

                    for (Request req : requestItems) {
                        if (req.getItemName().equalsIgnoreCase(selectedName)) {
                            JOptionPane.showMessageDialog(panel,
                                "Item Code: " + req.getItemCode() + 
                                "\nItem Name: " + req.getItemName() + 
                                "\nQuantity: " + req.getQuantity() + 
                                "\nUnit: " + req.getUnit() + 
                                "\nStatus: " + req.getStatus());
                            break;
                        }
                    }
                    popup.setVisible(false);
                }
            }
        });
    }

    private void applySorting()
    {
        TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) requestStatusTbl.getRowSorter();

        String sortBy = sortByComboBox.getSelectedItem().toString();
        String order = orderComboBox.getSelectedItem().toString();

        int columnIndex = 0;

        switch(sortBy)
        {
            case "Name":
                columnIndex = 1;
                break;
            case "Status":
                columnIndex = 4;
                break;
        }

        SortOrder sortOrder = order.equals("Ascending")
            ? SortOrder.ASCENDING : SortOrder.DESCENDING;
        
        List<RowSorter.SortKey> newKeys = new ArrayList<>();
        newKeys.add(new RowSorter.SortKey(columnIndex, sortOrder));

        sorter.setSortKeys(newKeys);
        sorter.sort();
    }

    //diplays JOptionPane if the head want to Approve or Reject the item to be requested by the staff
    private void approveOrReject(User loginUser, JPanel panel)
    {
        requestStatusTbl.addMouseListener(new MouseAdapter() 
        {
            public void mouseClicked(MouseEvent evt)
            {
                int viewRow = requestStatusTbl.rowAtPoint(evt.getPoint());
                if (viewRow < 0) return;

                int modelRow = requestStatusTbl.convertRowIndexToModel(viewRow);
                int col = requestStatusTbl.columnAtPoint(evt.getPoint());

                if (col != 4) return;

                if (modelRow < 0 || modelRow >= displayedRequests.size()) return;

                Request req = displayedRequests.get(modelRow);
                String status = req.getStatus();

                if(loginUser.getRole().equalsIgnoreCase("head"))
                {
                    if ("Completed".equalsIgnoreCase(status)) {
                        JOptionPane.showMessageDialog(
                            panel,
                            "This request is already completed.",
                            "Info",
                            JOptionPane.INFORMATION_MESSAGE
                        );
                        return;
                    }

                    if(!"Pending".equalsIgnoreCase(status)) return;

                    int choice = JOptionPane.showOptionDialog(panel, 
                        "Item: " + req.getItemName() + 
                        "\nQuantity: " + req.getOriginalQuantity() + 
                        "\nUnit: " + req.getUnit(), "Request Approval", 
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, 
                        null, new String [] {"Approve", "Reject"}, "Approve");

                    if(choice == 0)
                    {
                        req.setStatus("Approved");
                        RequestManager requestManager = new RequestManager();
                        try {
                            requestManager.updateRequestStatus(requestFilePath, req);
                        } catch (IOException e) {
                            // TODO Auto-generated catch block
                            e.printStackTrace();
                        }
                    }
                    else if(choice == 1)
                    {
                        req.setStatus("Rejected");
                        RequestManager requestManager = new RequestManager();
                        try {
                           requestManager.updateRequestStatus(requestFilePath, req);
                        } catch (IOException e) {
                            // TODO Auto-generated catch block
                            e.printStackTrace();
                        }
                    }

                    requestStatusTbl.getModel().setValueAt(req.getStatus(), modelRow, col);
                }
                else if(loginUser.getRole().equalsIgnoreCase("admin"))
                {
                    if ("Completed".equalsIgnoreCase(status) || "Completed (Released Nothing)".equalsIgnoreCase(status)) {
                        JOptionPane.showMessageDialog(
                            panel,
                            "This request is already completed.",
                            "Info",
                            JOptionPane.INFORMATION_MESSAGE
                        );
                        return;
                    }


                    if("Pending".equalsIgnoreCase(status))
                    {
                        JOptionPane.showMessageDialog(panel,"Cannot be processed yet. Wait for head approval.");
                        return;
                    }

                    else if ("Approved".equalsIgnoreCase(status))
                    {
                        int choice = JOptionPane.showConfirmDialog(
                            panel,
                            "Prepare this request for Pick Up?\nInventory will be checked.",
                            "Process Request",
                            JOptionPane.YES_NO_OPTION
                        );

                        if (choice != JOptionPane.YES_OPTION) return;

                        try {
                            ItemsManager itemsManager = new ItemsManager();
                            int releasedQty = itemsManager.deductInventory(req);

                            if (releasedQty == 0)
                            {
                                req.setStatus("Released Nothing");
                                req.setQuantity(releasedQty);
                                req.setDateCompleted(LocalDate.now()); // completion date
                                JOptionPane.showMessageDialog(
                                    panel,
                                    "No inventory available.\nNothing was released.",
                                    "Inventory Warning",
                                    JOptionPane.WARNING_MESSAGE
                                );
                            }

                            else if (releasedQty < req.getOriginalQuantity())
                            {
                                req.setStatus("Partially For Pick Up");
                                req.setQuantity(releasedQty);
                                JOptionPane.showMessageDialog(
                                    panel,
                                    "Only " + releasedQty + " was released.\nRemaining items unavailable.",
                                    "Partial Release",
                                    JOptionPane.WARNING_MESSAGE
                                );
                            }
                            else
                            {
                                req.setStatus("For Pick Up");
                            }
                            RequestManager rm = new RequestManager();
                            rm.updateRequestStatus(requestFilePath, req);

                        } catch (IOException e) {
                            e.printStackTrace();
                            JOptionPane.showMessageDialog(
                                panel,
                                "Inventory check failed.",
                                "Error",
                                JOptionPane.ERROR_MESSAGE
                            );
                            return;
                        }
                    }

                    else if("For Pick Up".equalsIgnoreCase(status) || "Partially For Pick Up".equalsIgnoreCase(status))
                    {
                        {
                            int choice = JOptionPane.showConfirmDialog(
                                panel,
                                "Mark this request as Completed?",
                                "Complete Request",
                                JOptionPane.YES_NO_OPTION
                            );

                            if (choice == JOptionPane.YES_OPTION) {
                                req.setStatus("Completed");
                                req.setDateCompleted(LocalDate.now()); // completion date

                                RequestManager rm = new RequestManager();
                                try {
                                    rm.updateRequestStatus(requestFilePath, req);
                                } catch (IOException e) {
                                    // TODO Auto-generated catch block
                                    e.printStackTrace();
                                }
                            }
                        }
                    }
                }
                else return;

                requestStatusTbl.getModel().setValueAt(req.getStatus(), modelRow, col);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deptNameLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JComboBox<String> requestIDComboBox;
    private javax.swing.JTable requestStatusTbl;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JComboBox<String> sortByComboBox;
    // End of variables declaration//GEN-END:variables
}
