/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.auxiliary;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.Set;
import java.util.regex.Pattern;
import javax.swing.RowFilter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

import java.awt.event.MouseEvent;

/**
 *
 * @author USER
 */
public class TransactionPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestStatusPanel
     */
    public TransactionPanel() {
        this.type = null;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        departmentNameLbl = new javax.swing.JLabel();
        requestIDComboBox = new javax.swing.JComboBox<>();
        searchTxtField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        releasedOrDeliveredBy = new javax.swing.JLabel();
        orderComboBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transactionTbl = new javax.swing.JTable();
        userNameComboBox = new javax.swing.JComboBox<>();
        requesterOrReceiverLbl = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        releasedOrDeliveredByLbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(5, 10, 36));
        setPreferredSize(new java.awt.Dimension(845, 480));

        departmentNameLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        departmentNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        departmentNameLbl.setText("Transaction History");

        requestIDComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        searchTxtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Search");

        releasedOrDeliveredBy.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        releasedOrDeliveredBy.setForeground(new java.awt.Color(255, 255, 255));
        releasedOrDeliveredBy.setText("Sort By");

        orderComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Order");

        transactionTbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        transactionTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(transactionTbl);

        userNameComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N

        requesterOrReceiverLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        requesterOrReceiverLbl.setForeground(new java.awt.Color(255, 255, 255));
        requesterOrReceiverLbl.setText("User Name");

        jLabel6.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Request/Delivery ID");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        releasedOrDeliveredByLbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        releasedOrDeliveredByLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(releasedOrDeliveredByLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(releasedOrDeliveredByLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(departmentNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(userNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(8, 8, 8)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(requestIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(releasedOrDeliveredBy, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 785, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(requesterOrReceiverLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(departmentNameLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requesterOrReceiverLbl)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(requestIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel4)
                        .addComponent(releasedOrDeliveredBy)
                        .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );
    }// </editor-fold>//GEN-END:initComponents


    private final TransactionType type;
    private String sourceName;
    // store the transactions provided to this panel (already pre-filtered by caller)
    private List<Transaction> panelTransactions = new ArrayList<>();
    private Map<String, Map<String, List<Transaction>>> userTransactionMap = new LinkedHashMap<>();


    public TransactionPanel(List<Transaction> transactions, TransactionType type, String source) throws IOException
    {
        initComponents();
        this.type = type;
        this.panelTransactions = transactions == null ? new ArrayList<>() : new ArrayList<>(transactions);
        this.sourceName = source;

        // populate combo box with distinct transaction IDs for the given type,
        // ordered so the latest transaction IDs (by dateCreated) appear first
        /*java.util.Map<String, LocalDate> latestDateById = new java.util.LinkedHashMap<>();
        for (Transaction t : panelTransactions) {
            if (t.getType() != type) continue;
            String id = t.getTransactionId();
            LocalDate d = t.getDateCreated();
            if (d == null) d = LocalDate.MIN;
            LocalDate prev = latestDateById.get(id);
            if (prev == null || d.isAfter(prev)) latestDateById.put(id, d);
        }

        //sort IDs by date descending (latest first)
        List<String> sortedIds = new ArrayList<>(latestDateById.keySet());
        sortedIds.sort((a, b) -> latestDateById.get(b).compareTo(latestDateById.get(a)));

        requestIDComboBox.removeAllItems();
        for (String id : sortedIds) requestIDComboBox.addItem(id);

        //when an id is selected, filter transactions and load them to table
        requestIDComboBox.addActionListener(e ->
            {
                try {
                    Object sel = requestIDComboBox.getSelectedItem();
                    if (sel == null) return;
                    String selected = sel.toString();
                    List<Transaction> filtered = new ArrayList<>();
                    for (Transaction t : transactions) {
                        if (t.getType() == type && t.getTransactionId().equals(selected)) filtered.add(t);
                    }
                    loadTransactions(filtered, source);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(TransactionPanel.this, "Error loading transactions: " + ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        );

        // initialize selection if available
        if (requestIDComboBox.getItemCount() > 0) {
            requestIDComboBox.setSelectedIndex(0);
            // trigger initial load
            requestIDComboBox.getActionListeners()[0].actionPerformed(null);
        }*/

        for (Transaction t : panelTransactions) {
            if (t.getType() != type) continue;

            String user = t.getUserName();
            String txId = t.getTransactionId();

            userTransactionMap
                .computeIfAbsent(user, k -> new LinkedHashMap<>())
                .computeIfAbsent(txId, k -> new ArrayList<>())
                .add(t);
        }

        userNameComboBox.removeAllItems();

        for (String user : userTransactionMap.keySet()) {
            userNameComboBox.addItem(user);
        }

        userNameComboBox.addActionListener(e -> {
            Object sel = userNameComboBox.getSelectedItem();
            if (sel == null) return;

            loadTransactionIdsForUser(sel.toString());
        });

        requestIDComboBox.addActionListener(e -> {
            Object sel = requestIDComboBox.getSelectedItem();
            if (sel == null) return;

            String txId = sel.toString();
            String user = userNameComboBox.getSelectedItem().toString();

            List<Transaction> list = userTransactionMap
                .get(user)
                .get(txId);

            loadTransactions(list, sourceName);
        });

        if (userNameComboBox.getItemCount() > 0) {
            userNameComboBox.setSelectedIndex(0);
        }

        // wire up search for transactions (works for both request and delivery)
        searching(transactions);

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(transactionTbl.getModel());
        transactionTbl.setRowSorter(sorter);

        orderComboBox.addActionListener(e -> applySorting());

    }

    private void loadTransactionIdsForUser(String user) {
        requestIDComboBox.removeAllItems();

        Map<String, List<Transaction>> txMap = userTransactionMap.get(user);
        if (txMap == null || txMap.isEmpty()) {
            clearTable();
            return;
        }

        Map<String, LocalDate> latestDateById = new HashMap<>();

        for (Map.Entry<String, List<Transaction>> e : txMap.entrySet()) {
            LocalDate latest = LocalDate.MIN;
            for (Transaction t : e.getValue()) {
                if (t.getDateCreated() != null && t.getDateCreated().isAfter(latest)) {
                    latest = t.getDateCreated();
                }
            }
            latestDateById.put(e.getKey(), latest);
        }

        List<String> sortedIds = new ArrayList<>(latestDateById.keySet());
        sortedIds.sort((a, b) -> latestDateById.get(b).compareTo(latestDateById.get(a)));

        for (String id : sortedIds) {
            requestIDComboBox.addItem(id);
        }

        // 🔥 auto-load latest
        requestIDComboBox.setSelectedIndex(0);
    }
    private void clearTable() {
        DefaultTableModel model = (DefaultTableModel) transactionTbl.getModel();
        model.setRowCount(0);
    }



    //public accessors used by GUITransactions to export receipts
    public String getSelectedTransactionId() {
        Object sel = requestIDComboBox.getSelectedItem();
        return sel == null ? null : sel.toString();
    }

    //to get the transaction for the selected id in the combobox, from getSelectedTransactionId();
    public List<Transaction> getTransactionsForSelectedId() {
        String selected = getSelectedTransactionId();
        if (selected == null) return new ArrayList<>();
        List<Transaction> filtered = new ArrayList<>();
        for (Transaction t : panelTransactions) {
            if (t.getType() == type && selected.equals(t.getTransactionId())) filtered.add(t);
        }
        return filtered;
    }

    public TransactionType getTransactionType() { return this.type; }

    public String getSourceName() { return this.sourceName; }
    
    public List<Transaction> getAllTransactions() {
        return new ArrayList<>(this.panelTransactions);
    }

    //set up the table for the transactions, depending if requests or delivers
    private void loadTransactions(List<Transaction> transactions, String source)
    {
        //if there are no transactions for this selection, clear the table model
        if(transactions == null || transactions.isEmpty()) {
            DefaultTableModel emptyModel;
            if (type == TransactionType.REQUEST) {
                emptyModel = new DefaultTableModel(
                    new String[] {"Item Code", "Item Name", "Quantity", "Unit", "Date Requested", "Date Completed"}, 0
                );
            } else {
                emptyModel = new DefaultTableModel(
                    new String[] {"Item Code", "Item Name", "Quantity", "Unit", "Date Delivered", "Date Completed"}, 0
                );
            }
            transactionTbl.setModel(emptyModel);
            return;
        }

        DefaultTableModel model;;

        if (type == TransactionType.REQUEST) 
        {
            model = new DefaultTableModel(
                new String[] {"Item Code", "Item Name", "Quantity", "To Release", "Unit", "Date Requested", "Date Approved", "Date Completed"}, 0
            );
        } 
        else 
        { // DELIVERY
            model = new DefaultTableModel(
                new String[] {"Item Code", "Item Name", "Quantity", "Unit", "Date Delivered", "Date Completed"}, 0
            );
        }

        model.setRowCount(0);

        for(Transaction t : transactions)
        {
            try {
                if (type == TransactionType.REQUEST) 
                {
                    //only include requests that are completed or released nothing
                    boolean completed = t.getDateCompleted() != null;
                    boolean releasedNothing = t.getStatus() != null && (t.getStatus().equalsIgnoreCase("Released Nothing") || t.getStatus().equalsIgnoreCase("Partially Released"));
                    if (!completed && !releasedNothing) continue;

                    int cols = model.getColumnCount();
                    Object[] row = new Object[cols];
                    row[0] = t.getItemCode();
                    row[1] = t.getItemName();
                    row[2] = t.getQuantity();
                    row[3] = t.getQuantityToBeReleased();
                    row[4] = t.getUnit();
                    if (cols > 5) row[5] = t.getDateCreated();
                    if (cols > 7) row[6] = t.getDateApproved();
                    if (cols > 7) row[7] = t.getDateCompleted();
                    
                    model.addRow(row);

                    requesterOrReceiverLbl.setText("Requested By");
                    releasedOrDeliveredBy.setText("Released By");
                    releasedOrDeliveredByLbl.setText(t.getReleasedOrDeliveredBy());
                } 
                else 
                { 
                    // DELIVERY
                    int cols = model.getColumnCount();
                    Object[] row = new Object[cols];
                    row[0] = t.getItemCode();
                    row[1] = t.getItemName();
                    row[2] = t.getQuantity();
                    row[3] = t.getUnit();
                    if (cols > 4) row[4] = t.getDateCreated();
                    if (cols > 5) row[5] = t.getDateCompleted();
                    
                    model.addRow(row);

                    requesterOrReceiverLbl.setText("Received By");
                    releasedOrDeliveredBy.setText("Delivered By");
                    releasedOrDeliveredByLbl.setText(t.getReleasedOrDeliveredBy());
                }
            } catch (Exception ex) {
                //log the problematic transaction and continue so one bad line doesn't break the entire view
                System.err.println("Error adding transaction to table for ID=" + (t==null?"<null>":t.getTransactionId()) + ": " + ex);
                ex.printStackTrace();
                continue;
            }
        }
        transactionTbl.setModel(model);

        //ensure sorter matches the new model
        TableRowSorter<TableModel> newSorter = new TableRowSorter<>(transactionTbl.getModel());
        transactionTbl.setRowSorter(newSorter);

        transactionTbl.setFillsViewportHeight(true);
        transactionTbl.setRowHeight(24);

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                        boolean isSelected, boolean hasFocus,
                                                        int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                setHorizontalAlignment(JLabel.CENTER);
                
                if (!isSelected) {
                    c.setBackground(row % 2 == 1 ? new Color(245,245, 245) : Color.WHITE);
                }

                return c;
            }
        };

        for (int i = 0; i < transactionTbl.getColumnCount(); i++) {
            transactionTbl.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }
    }

    //for searching
    private void searching(List<Transaction> transactions)
    {
        JPopupMenu popup = new JPopupMenu();
        popup.setFocusable(true);

        JList<String> suggestionList = new JList<>();
        JScrollPane scrollPane = new JScrollPane(suggestionList);
        scrollPane.setPreferredSize(new Dimension(Math.max(searchTxtField.getPreferredSize().width, 200), 100));
        popup.add(scrollPane);
        popup.setInvoker(searchTxtField);

        searchTxtField.getDocument().addDocumentListener(new DocumentListener() {
            public void update()
            {
                Object selectedObj = requestIDComboBox.getSelectedItem();
                if(selectedObj == null) return;
                String selectedId = selectedObj.toString();

                // filter transactions by selected id and type
                List<Transaction> transForId = new ArrayList<>();
                for (Transaction t : transactions) {
                    if (t.getType() == type && t.getTransactionId().equals(selectedId)) transForId.add(t);
                }

                String text = searchTxtField.getText().toLowerCase();

                DefaultListModel<String> model = new DefaultListModel<>();

                for (Transaction t : transForId) {
                    if (text.isEmpty() || t.getItemName().toLowerCase().contains(text)) {
                        model.addElement(t.getItemName() + "(" + t.getTransactionId() + ")");
                    }
                }

                suggestionList.setModel(model);

                // apply row filter to table (filter by item name column index 1)
                TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) transactionTbl.getRowSorter();
                if (sorter != null) {
                    if (text.isEmpty()) {
                        sorter.setRowFilter(null);
                    } else {
                        try {
                            sorter.setRowFilter(RowFilter.regexFilter("(?i)" + Pattern.quote(text), 1));
                        } catch (Exception ex) {
                            sorter.setRowFilter(null);
                        }
                    }
                }

                if (!model.isEmpty()) {
                    int width = Math.max(searchTxtField.getWidth(), searchTxtField.getPreferredSize().width);
                    if (width <= 0) width = Math.max(searchTxtField.getPreferredSize().width, 200);
                    scrollPane.setPreferredSize(new Dimension(width, 100));

                    if(!popup.isVisible()) {
                        SwingUtilities.invokeLater(() -> {
                            popup.show(searchTxtField, 0, searchTxtField.getHeight());
                            searchTxtField.requestFocusInWindow();
                        });
                    }
                    popup.revalidate();
                    popup.repaint();
                } else {
                    popup.setVisible(false);
                }
            }
            @Override
            public void insertUpdate(DocumentEvent e) { update(); }
            @Override
            public void removeUpdate(DocumentEvent e) { update(); }
            @Override
            public void changedUpdate(DocumentEvent e) { update(); }
        });

        //to display as a JOptionPane the Transaction Details
        suggestionList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                String selected = suggestionList.getSelectedValue();
                if (selected == null) return;

                String selectedName = selected.split("\\(")[0].trim();
                String selectedId = null;
                int idx = selected.lastIndexOf('(');
                if (idx != -1 && selected.endsWith(")")) {
                    selectedId = selected.substring(idx + 1, selected.length() - 1).trim();
                }

                // find matching transaction from the provided transactions list
                Transaction match = null;
                for (Transaction t : transactions) {
                    if (t.getType() == type) {
                        boolean idMatches = (selectedId == null) || selectedId.equals(t.getTransactionId());
                        if (idMatches && t.getItemName().equalsIgnoreCase(selectedName)) {
                            match = t;
                            break;
                        }
                    }
                }

                if (match != null) {
                    StringBuilder msg = new StringBuilder();
                    msg.append("Item Code: ").append(match.getItemCode())
                       .append("\nItem Name: ").append(match.getItemName())
                       .append("\nQuantity: ").append(match.getQuantity())
                       .append("\nUnit: ").append(match.getUnit())
                       .append("\nSource: ").append(match.getSource() == null ? "" : match.getSource())
                       .append("\nDate Created: ").append(match.getDateCreated() == null ? "" : match.getDateCreated())
                       .append("\nDate Completed: ").append(match.getDateCompleted() == null ? "" : match.getDateCompleted());

                    JOptionPane.showMessageDialog(TransactionPanel.this, msg.toString(), "Transaction Details", JOptionPane.INFORMATION_MESSAGE);
                }

                popup.setVisible(false);
            }
        });
    }

    //to apply sorting
    private void applySorting()
    {
        TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) transactionTbl.getRowSorter();

        String order = orderComboBox.getSelectedItem().toString();

        int columnIndex = 0;

        SortOrder sortOrder = order.equals("Ascending")
            ? SortOrder.ASCENDING : SortOrder.DESCENDING;
        
        List<RowSorter.SortKey> newKeys = new ArrayList<>();
        newKeys.add(new RowSorter.SortKey(columnIndex, sortOrder));

        sorter.setSortKeys(newKeys);
        sorter.sort();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel departmentNameLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JLabel releasedOrDeliveredBy;
    private javax.swing.JLabel releasedOrDeliveredByLbl;
    private javax.swing.JComboBox<String> requestIDComboBox;
    private javax.swing.JLabel requesterOrReceiverLbl;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JTable transactionTbl;
    private javax.swing.JComboBox<String> userNameComboBox;
    // End of variables declaration//GEN-END:variables
}
