/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopdsaproject;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.List;
import java.util.Map;

import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class GUIRequestStatus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIRequestStatus.class.getName());

    /**
     * Creates new form GUIRequestStatus
     */
    public GUIRequestStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestStatusPnl = new javax.swing.JPanel();
        departmentNameLbl = new javax.swing.JLabel();
        requestIDComboBox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestStatusTbl = new javax.swing.JTable();
        homeLbl = new javax.swing.JLabel();
        createRequestLbl = new javax.swing.JLabel();
        requestStatusLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestStatusPnl.setBackground(new java.awt.Color(255, 255, 255));

        departmentNameLbl.setText("request Status");

        requestStatusTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit", "Request Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestStatusTbl);

        homeLbl.setText("Home");

        createRequestLbl.setText("Create Request");

        requestStatusLbl.setText("Request Status");

        javax.swing.GroupLayout requestStatusPnlLayout = new javax.swing.GroupLayout(requestStatusPnl);
        requestStatusPnl.setLayout(requestStatusPnlLayout);
        requestStatusPnlLayout.setHorizontalGroup(
            requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestStatusPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(createRequestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestStatusLbl)
                .addGap(141, 141, 141))
            .addGroup(requestStatusPnlLayout.createSequentialGroup()
                .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestStatusPnlLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(departmentNameLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(requestIDComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 697, Short.MAX_VALUE))))
                    .addGroup(requestStatusPnlLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 782, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        requestStatusPnlLayout.setVerticalGroup(
            requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestStatusPnlLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLbl)
                    .addComponent(createRequestLbl)
                    .addComponent(requestStatusLbl))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(departmentNameLbl)
                .addGap(41, 41, 41)
                .addComponent(requestIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestStatusPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(requestStatusPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIRequestStatus().setVisible(true));
    }

    private Map<String, List<Request>> requestsMap;   // <-- CLASS FIELD
    private RequestManager requestManager;

    public GUIRequestStatus(User loginUser) throws IOException
    {
        initComponents();

        setLbl(loginUser);

        requestManager = new RequestManager();
        requestsMap = requestManager.loadAllRequests(loginUser.getFilePath());

        for(String requestId : requestsMap.keySet())
        {
            requestIDComboBox.addItem(requestId);
        }

        if(!requestsMap.isEmpty())
        {
            String latestId = getLatestRequestID();
            requestIDComboBox.setSelectedItem(latestId);
            loadRequestOnTable(latestId);
        }

        requestIDComboBox.addActionListener(e ->
            {
                String selected = requestIDComboBox.getSelectedItem().toString();
                loadRequestOnTable(selected);
            }
        );


    }




    private void setLbl(User loginUser)
    {
        homeLbl.setFont(new Font("Verdana", Font.PLAIN, 12));
        homeLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homeLbl.setToolTipText("Go back Home");
        homeLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                if(loginUser.getRole().equals("head"))
                {
                    GUIHeadDashboard headDashboard = new GUIHeadDashboard(loginUser);
                    headDashboard.setVisible(true);
                }
                else if(loginUser.getRole().equals("staff"))
                {
                    GUIStaffDashboard staffDashboard = new GUIStaffDashboard(loginUser);
                    staffDashboard.setVisible(true);
                }
                dispose();
            }
        });

        createRequestLbl.setFont(new Font("Verdana", Font.PLAIN, 12));
        createRequestLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        createRequestLbl.setToolTipText("Create New Request");
        createRequestLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUIRequestInventory requestInventory = new GUIRequestInventory(loginUser);
                requestInventory.setVisible(true);
                dispose();
            }
        });

        requestStatusLbl.setFont(new Font("Verdana", Font.BOLD, 12));
        
    }

    private void loadRequestOnTable(String requestId)
    {
        List<Request> list = requestsMap.get(requestId);

        DefaultTableModel model = (DefaultTableModel) requestStatusTbl.getModel();
        model.setRowCount(0);

        for(Request req : list){
            model.addRow(new Object[]
                {
                    req.getItemCode(), req.getItemName(), req.getQuantity(), req.getUnit(), req.getStatus()
                }
            );
        }

        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        requestStatusTbl.getColumnModel().getColumn(2).setCellRenderer(center);
    }

    private String getLatestRequestID() 
    {
        return requestsMap.keySet().stream()
                .sorted()
                .reduce((first, second) -> second)  // get last
                .orElse(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createRequestLbl;
    private javax.swing.JLabel departmentNameLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> requestIDComboBox;
    private javax.swing.JLabel requestStatusLbl;
    private javax.swing.JPanel requestStatusPnl;
    private javax.swing.JTable requestStatusTbl;
    // End of variables declaration//GEN-END:variables
}
