/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopdsaproject;

import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class GUIRequestInventory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIRequestInventory.class.getName());

    /**
     * Creates new form GUIRequestInventory
     */
    public GUIRequestInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestInventoryPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestInventoryTbl = new javax.swing.JTable();
        homeLbl = new javax.swing.JLabel();
        requestLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderComboBox = new javax.swing.JComboBox<>();
        searchTxtField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestInventoryPnl.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Request Inventory");

        requestInventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit", "Request Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestInventoryTbl);

        homeLbl.setText("Home");

        requestLbl.setText("Request");

        jLabel5.setText("Order:");

        jLabel4.setText("Search:");

        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));

        searchTxtField.addActionListener(this::searchTxtFieldActionPerformed);

        javax.swing.GroupLayout requestInventoryPnlLayout = new javax.swing.GroupLayout(requestInventoryPnl);
        requestInventoryPnl.setLayout(requestInventoryPnlLayout);
        requestInventoryPnlLayout.setHorizontalGroup(
            requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                        .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(requestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                        .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(51, 51, 51)
                                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(98, 98, 98))))
        );
        requestInventoryPnlLayout.setVerticalGroup(
            requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLbl)
                    .addComponent(requestLbl))
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchTxtField)
                            .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestInventoryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestInventoryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIRequestInventory().setVisible(true));
    }

    public GUIRequestInventory(User loginUser)
    {
        initComponents();

        homeLbl.setFont(new Font("Verdana", Font.PLAIN, 12));
        homeLbl.setToolTipText("Go back to Home");
        homeLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homeLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                if(loginUser.equals("head"))
                {
                    GUIHeadDashboard headDashboard = new GUIHeadDashboard(loginUser);
                    headDashboard.setVisible(true);
                }
                else
                {
                    GUIStaffDashboard staffDashboard = new GUIStaffDashboard(loginUser);
                    staffDashboard.setVisible(true);
                }
                dispose();
            }
        });

        requestLbl.setFont(new Font("Verdana", Font.BOLD, 12));
        

        ItemsManager itemsManager = new ItemsManager();
        itemsManager.loadInventory();
        List<Items> itemList = itemsManager.getItems();

        DefaultTableModel model = (DefaultTableModel) requestInventoryTbl.getModel();
        model.setRowCount(0);

        DefaultTableCellRenderer center = new DefaultTableCellRenderer();
        center.setHorizontalAlignment(JLabel.CENTER);
        requestInventoryTbl.getColumnModel().getColumn(2).setCellRenderer(center);

        for(Items item : itemsManager.getItems())
        {
            model.addRow(new Object[]
                {
                    item.getItemCode(),
                    item.getItemName(),
                    item.getQuantity(),
                    item.getUnit(),
                    null
                }
            );
        }

        JPopupMenu popup = new JPopupMenu();
        popup.setFocusable(false);

        JList<String> suggestionList = new JList<>();
        JScrollPane scrollPane = new JScrollPane(suggestionList);
        scrollPane.setPreferredSize(new Dimension(searchTxtField.getWidth(), 100));
        popup.add(scrollPane);

        searchTxtField.getDocument().addDocumentListener(new DocumentListener() {
            public void update()
            {
                String text = searchTxtField.getText().toLowerCase();
                DefaultListModel<String> model = new DefaultListModel<>();

                for (Items item : itemList) {
                    if (item.getItemName().toLowerCase().contains(text) && !text.isEmpty()) {
                        model.addElement(item.getItemName());
                    }
                }
                suggestionList.setModel(model);

                if (!model.isEmpty()) {
                    popup.show(searchTxtField, 0, searchTxtField.getHeight());
                } else {
                    popup.setVisible(false);
                }
            }
            @Override
            public void insertUpdate(DocumentEvent e) { update(); }
            @Override
            public void removeUpdate(DocumentEvent e) { update(); }
            @Override
            public void changedUpdate(DocumentEvent e) { update(); }
        });

        suggestionList.addMouseListener((new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                String selectedName = suggestionList.getSelectedValue();
                if(selectedName == null) return;

                searchTxtField.setText(selectedName);
                popup.setVisible(false);

                moveRowToTop(selectedName);
            }
        }));

        TableRowSorter<TableModel> sorter = new TableRowSorter<>(requestInventoryTbl.getModel());
        requestInventoryTbl.setRowSorter(sorter);

        orderComboBox.addActionListener(e -> applySorting());

    }

    private void moveRowToTop(String name) {
        DefaultTableModel model = (DefaultTableModel) requestInventoryTbl.getModel();

        RowSorter oldSorter = requestInventoryTbl.getRowSorter();
        requestInventoryTbl.setRowSorter(null);

        Vector targetRow = null;
        int targetIndex = -1;

        // Find selected row
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 1).toString().equals(name)) { 
                targetRow = (Vector) model.getDataVector().get(i);
                targetIndex = i;
                break;
            }
        }

        if (targetRow == null) return;

        // Remove and reinsert at top
        model.removeRow(targetIndex);
        model.insertRow(0, targetRow);

        requestInventoryTbl.setRowSorter(oldSorter);
    }

    private void applySorting()
    {
        TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) requestInventoryTbl.getRowSorter();

        String order = orderComboBox.getSelectedItem().toString();

        int columnIndex = 0;

        SortOrder sortOrder = order.equals("Ascending")
            ? SortOrder.ASCENDING : SortOrder.DESCENDING;
        
        List<RowSorter.SortKey> newKeys = new ArrayList<>();
        newKeys.add(new RowSorter.SortKey(columnIndex, sortOrder));

        sorter.setSortKeys(newKeys);
        sorter.sort();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JPanel requestInventoryPnl;
    private javax.swing.JTable requestInventoryTbl;
    private javax.swing.JLabel requestLbl;
    private javax.swing.JTextField searchTxtField;
    // End of variables declaration//GEN-END:variables
}
