/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oopdsaproject;

import java.awt.BorderLayout;
import java.util.List;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.swing.JPanel;
import javax.swing.JTabbedPane;

/**
 *
 * @author USER
 */
public class GUITransactions extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUITransactions.class.getName());

    /**
     * Creates new form GUITransactions
     */
    public GUITransactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactionsPnl = new javax.swing.JPanel();
        transactionsTabbedPane = new javax.swing.JTabbedPane();
        requestsTabbedPane = new javax.swing.JTabbedPane();
        jLabel1 = new javax.swing.JLabel();
        homeLbl = new javax.swing.JLabel();
        inventoryLbl = new javax.swing.JLabel();
        requestsLbl = new javax.swing.JLabel();
        deliveriesLbl = new javax.swing.JLabel();
        transactionsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transactionsPnl.setBackground(new java.awt.Color(255, 255, 255));

        transactionsTabbedPane.addTab("tab1", requestsTabbedPane);

        jLabel1.setText("Transactions");

        homeLbl.setText("Home");

        inventoryLbl.setText("Inventory");

        requestsLbl.setText("Requests");

        deliveriesLbl.setText("Deliveries");

        transactionsLbl.setText("Transactions");

        javax.swing.GroupLayout transactionsPnlLayout = new javax.swing.GroupLayout(transactionsPnl);
        transactionsPnl.setLayout(transactionsPnlLayout);
        transactionsPnlLayout.setHorizontalGroup(
            transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPnlLayout.createSequentialGroup()
                .addGroup(transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionsPnlLayout.createSequentialGroup()
                        .addGap(282, 282, 282)
                        .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inventoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(requestsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deliveriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(transactionsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactionsPnlLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPnlLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(transactionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 803, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        transactionsPnlLayout.setVerticalGroup(
            transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPnlLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLbl)
                    .addComponent(inventoryLbl)
                    .addComponent(requestsLbl)
                    .addComponent(deliveriesLbl)
                    .addComponent(transactionsLbl))
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(transactionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transactionsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transactionsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUITransactions().setVisible(true));
    }

    private User loginUser;
    private TransactionManager transactionManager;

    public GUITransactions(User loginUser) throws IOException
    {
        this.loginUser = loginUser;
        initComponents();

        transactionManager = new TransactionManager();
        List<Transaction> transactions = transactionManager.loadAllTransactions();

        setupRequestTabs(transactions);
        setupDeliveryTab(transactions);
    }

    private void setupRequestTabs(List<Transaction> allTransactions) throws IOException {
        requestsTabbedPane = new JTabbedPane();

        for (String dept : transactionManager.getDeptFiles().keySet()) {
            List<Transaction> deptTransactions = allTransactions.stream()
                .filter(t -> t.getType() == TransactionType.REQUEST)
                .filter(t -> t.getSource().equals(dept))
                .toList();

            TransactionPanel panel = new TransactionPanel(deptTransactions, TransactionType.REQUEST, "Department");
            requestsTabbedPane.addTab(dept, panel);
        }
        if(transactionsTabbedPane.getTabCount() > 0) { transactionsTabbedPane.remove(0);}
        transactionsTabbedPane.addTab("Requests", requestsTabbedPane);
    }

    private void setupDeliveryTab(List<Transaction> allTransactions) throws IOException {
        List<Transaction> deliveryTransactions = allTransactions.stream()
            .filter(t -> t.getType() == TransactionType.DELIVERY)
            .toList();

        TransactionPanel deliveryPanel = new TransactionPanel(deliveryTransactions, TransactionType.DELIVERY, "Supplier");
        transactionsTabbedPane.addTab("Deliveries", deliveryPanel);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deliveriesLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel inventoryLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel requestsLbl;
    private javax.swing.JTabbedPane requestsTabbedPane;
    private javax.swing.JLabel transactionsLbl;
    private javax.swing.JPanel transactionsPnl;
    private javax.swing.JTabbedPane transactionsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
