/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

/**
 *
 * @author USER
 */
public class GUIAdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIAdminDashboard.class.getName());

    /**
     * Creates new form GUIAdminDashboard
     */
    public GUIAdminDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminDashboardPnl = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        inventoryLbl = new javax.swing.JLabel();
        requestsLbl = new javax.swing.JLabel();
        deliveriesLbl = new javax.swing.JLabel();
        transactionsLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        welcomeLbl = new javax.swing.JLabel();
        toKosaLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        adminDashboardPnl.setBackground(new java.awt.Color(5, 10, 36));

        homeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLbl.setText("Home");

        inventoryLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        inventoryLbl.setForeground(new java.awt.Color(255, 255, 255));
        inventoryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventoryLbl.setText("Inventory");

        requestsLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestsLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestsLbl.setText("Requests");

        deliveriesLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        deliveriesLbl.setForeground(new java.awt.Color(255, 255, 255));
        deliveriesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveriesLbl.setText("Deliveries");

        transactionsLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        transactionsLbl.setForeground(new java.awt.Color(255, 255, 255));
        transactionsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionsLbl.setText("Transactions");

        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLbl.setText("jLabel2");

        toKosaLbl.setForeground(new java.awt.Color(255, 255, 255));
        toKosaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toKosaLbl.setText("jLabel3");

        descriptionLbl.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLbl.setText("jLabel4");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("About Us");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contact ");

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("KOSA");

        javax.swing.GroupLayout adminDashboardPnlLayout = new javax.swing.GroupLayout(adminDashboardPnl);
        adminDashboardPnl.setLayout(adminDashboardPnlLayout);
        adminDashboardPnlLayout.setHorizontalGroup(
            adminDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminDashboardPnlLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(inventoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deliveriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminDashboardPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(adminDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDashboardPnlLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(toKosaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(adminDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, adminDashboardPnlLayout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(descriptionLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcomeLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(296, 296, 296))
        );
        adminDashboardPnlLayout.setVerticalGroup(
            adminDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminDashboardPnlLayout.createSequentialGroup()
                .addGroup(adminDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminDashboardPnlLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(adminDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(homeLbl)
                            .addComponent(inventoryLbl)
                            .addComponent(requestsLbl)
                            .addComponent(deliveriesLbl)
                            .addComponent(transactionsLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminDashboardPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addGap(21, 21, 21)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toKosaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(adminDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDashboardPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(adminDashboardPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIAdminDashboard().setVisible(true));
    }

    public GUIAdminDashboard(User loginUser)
    {
        initComponents();

        homeLbl.setFont(new Font("Verdana", Font.BOLD, 14));

        inventoryLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        inventoryLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        inventoryLbl.setToolTipText("Go to Inventory");
        inventoryLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUIInventory inventoryForm = new GUIInventory(loginUser);
                inventoryForm.setVisible(true);
                dispose();
            }
        });

        requestsLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        requestsLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        requestsLbl.setToolTipText("View Requests of Departments");
        requestsLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                try {
                    GUIRequestStatusForAdmin requestStatus = new GUIRequestStatusForAdmin(loginUser);
                    requestStatus.setVisible(true);
                    dispose();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

                dispose();
            }
        });
        
        deliveriesLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        deliveriesLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        deliveriesLbl.setToolTipText("View Requests of Departments");
        deliveriesLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUIDeliveryInventory deliveryInventory = new GUIDeliveryInventory(loginUser);
                deliveryInventory.setVisible(true);
                dispose();
            }
        });

        transactionsLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        transactionsLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        transactionsLbl.setToolTipText("View All Transactions");
        transactionsLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUITransactions transactions;
                try {
                    transactions = new GUITransactions(loginUser);
                    transactions.setVisible(true);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                dispose();
            }
        });
        setWelcomeLbls();
    }
    
    private void setWelcomeLbls()
    {
        welcomeLbl.setText("Welcome");
        welcomeLbl.setFont(new Font("Verdana", Font.BOLD, 40));

        toKosaLbl.setText("to KOSA");
        toKosaLbl.setFont(new Font("Verdana", Font.BOLD, 20));

        String text = "<html>" + 
            "<center>Our centralized platform for efficiently managing and tracking<br>" + 
            "all office supplies. With KOSA, we can easily monitor inventory<br>" + 
            "levels, process staff requests, and ensure that every item is <br>" + 
            "issued accurately and on time. This system helps us stay<br>" + 
            "organized, maintain accountability, and support smooth<br>" +
            "operations across all departments.</center>" + "</html>";

        descriptionLbl.setText(text);
        descriptionLbl.setFont(new Font("Verdana", Font.PLAIN, 12));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminDashboardPnl;
    private javax.swing.JLabel deliveriesLbl;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel inventoryLbl;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel requestsLbl;
    private javax.swing.JLabel toKosaLbl;
    private javax.swing.JLabel transactionsLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
