/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class GUIDeliveryInventory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIDeliveryInventory.class.getName());

    /**
     * Creates new form GUIRequestInventory
     */
    public GUIDeliveryInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestInventoryPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        deliverInventoryTbl = new javax.swing.JTable();
        homeLbl = new javax.swing.JLabel();
        inventoryLbl = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderComboBox = new javax.swing.JComboBox<>();
        searchTxtField = new javax.swing.JTextField();
        viewRequestBtn = new javax.swing.JButton();
        deliverBtn = new javax.swing.JButton();
        requestStatusLbl = new javax.swing.JLabel();
        addNewItemBtn = new javax.swing.JButton();
        deliveriesLbl = new javax.swing.JLabel();
        transactionLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        logoutLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestInventoryPnl.setBackground(new java.awt.Color(5, 10, 36));

        deliverInventoryTbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        deliverInventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit", "Deliver Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(deliverInventoryTbl);

        homeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLbl.setText("Home");

        inventoryLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        inventoryLbl.setForeground(new java.awt.Color(255, 255, 255));
        inventoryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventoryLbl.setText("Inventory");

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order:");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search:");

        orderComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));

        searchTxtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        searchTxtField.addActionListener(this::searchTxtFieldActionPerformed);

        viewRequestBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        viewRequestBtn.setText("View Delivery");

        deliverBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        deliverBtn.setText("Deliver");

        requestStatusLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestStatusLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestStatusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestStatusLbl.setText("Requests");

        addNewItemBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        addNewItemBtn.setText("Add New Item");

        deliveriesLbl.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        deliveriesLbl.setForeground(new java.awt.Color(255, 255, 255));
        deliveriesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveriesLbl.setText("Deliveries");

        transactionLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        transactionLbl.setForeground(new java.awt.Color(255, 255, 255));
        transactionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionLbl.setText("Transactions");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        logoutLbl.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logoutLbl.setForeground(new java.awt.Color(255, 255, 255));
        logoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLbl.setText("KOSA");

        javax.swing.GroupLayout requestInventoryPnlLayout = new javax.swing.GroupLayout(requestInventoryPnl);
        requestInventoryPnl.setLayout(requestInventoryPnlLayout);
        requestInventoryPnlLayout.setHorizontalGroup(
            requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                        .addComponent(addNewItemBtn)
                        .addGap(32, 32, 32)
                        .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(deliverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                        .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(logoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(requestStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        requestInventoryPnlLayout.setVerticalGroup(
            requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                        .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transactionLbl)
                            .addComponent(deliveriesLbl)
                            .addComponent(requestStatusLbl)
                            .addComponent(inventoryLbl)
                            .addComponent(homeLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                        .addComponent(logoutLbl)
                        .addGap(20, 20, 20)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(orderComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchTxtField)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deliverBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNewItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestInventoryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestInventoryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIDeliveryInventory().setVisible(true));
    }


    //constructor for the Delivery inventory
    public GUIDeliveryInventory(User loginUser)
    {
        initComponents();

        //set labels
        // make logout behave like a logout button
        logoutLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        logoutLbl.setToolTipText("Logout");
        logoutLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                GUILogin login = new GUILogin();
                login.setVisible(true);
                dispose();
            }
        });

        homeLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        homeLbl.setToolTipText("Go back to Home");
        homeLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homeLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUIAdminDashboard adminDashboard = new GUIAdminDashboard(loginUser);
                adminDashboard.setVisible(true);
                dispose();
            }
        });

        inventoryLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        inventoryLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        inventoryLbl.setToolTipText("Go to Inventory");
        inventoryLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUIInventory inventoryForm = new GUIInventory(loginUser);
                inventoryForm.setVisible(true);
                dispose();
            }
        });

        requestStatusLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        requestStatusLbl.setToolTipText("View Request Status");
        requestStatusLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        requestStatusLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUITransactions transactions = null;
                try {
                    transactions = new GUITransactions(loginUser);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                transactions.setVisible(true);
                dispose();
            }
        });
        
        deliveriesLbl.setToolTipText("View Deliveries");

        transactionLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        transactionLbl.setToolTipText("View All Transactions");
        transactionLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        transactionLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUITransactions transactions;
                try {
                    transactions = new GUITransactions(loginUser);
                    transactions.setVisible(true);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                dispose();
            }
        });
        
        //load inventory
        ItemsManager itemsManager = new ItemsManager();
        itemsManager.loadInventory();
        List<Items> itemList = itemsManager.getItems();

        //to set the table
        DefaultTableModel model = (DefaultTableModel) deliverInventoryTbl.getModel();
        model.setRowCount(0);

        deliverInventoryTbl.setFillsViewportHeight(true);
        deliverInventoryTbl.setRowHeight(24);

        //alternating color
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                        boolean isSelected, boolean hasFocus,
                                                        int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                setHorizontalAlignment(JLabel.CENTER);
                
                if (!isSelected) {
                    c.setBackground(row % 2 == 1 ? new Color(245,245, 245) : Color.WHITE);
                }

                return c;
            }
        };

        for (int i = 0; i < deliverInventoryTbl.getColumnCount(); i++) {
            deliverInventoryTbl.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        //put the data about the items in the table
        for(Items item : itemsManager.getItems())
        {
            model.addRow(new Object[]
                {
                    item.getItemCode(),
                    item.getItemName(),
                    item.getQuantity(),
                    item.getUnit(),
                    null
                }
            );
        }

        //for the searching
        JPopupMenu popup = new JPopupMenu();
        popup.setFocusable(false);

        JList<String> suggestionList = new JList<>();
        JScrollPane scrollPane = new JScrollPane(suggestionList);
        scrollPane.setPreferredSize(new Dimension(searchTxtField.getWidth(), 100));
        popup.add(scrollPane);

        searchTxtField.getDocument().addDocumentListener(new DocumentListener() {
            public void update()
            {
                String text = searchTxtField.getText().toLowerCase();
                DefaultListModel<String> model = new DefaultListModel<>();

                for (Items item : itemList) {
                    if (item.getItemName().toLowerCase().contains(text) && !text.isEmpty()) {
                        model.addElement(item.getItemName());
                    }
                }
                suggestionList.setModel(model);

                if (!model.isEmpty()) {
                    popup.show(searchTxtField, 0, searchTxtField.getHeight());
                } else {
                    popup.setVisible(false);
                }
            }
            @Override
            public void insertUpdate(DocumentEvent e) { update(); }
            @Override
            public void removeUpdate(DocumentEvent e) { update(); }
            @Override
            public void changedUpdate(DocumentEvent e) { update(); }
        });

        suggestionList.addMouseListener((new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                String selectedName = suggestionList.getSelectedValue();
                if(selectedName == null) return;

                searchTxtField.setText(selectedName);
                popup.setVisible(false);

                moveRowToTop(selectedName);
            }
        }));

        //for sorting
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(deliverInventoryTbl.getModel());
        deliverInventoryTbl.setRowSorter(sorter);

        orderComboBox.addActionListener(e -> applySorting());

        //spinner for the quantity
        deliverInventoryTbl.getColumnModel().getColumn(4).setCellEditor(new SpinnerEditor(true));

        //view deliveries, variable name was reused
        viewRequestBtn.addActionListener(e -> showRequestedItems(deliverInventoryTbl));

        //instantiate DeliveryManager
        DeliveryManager deliveryManager = new DeliveryManager();
        //populate deliveryManager items from inventory file so deliveries can update inventory
        deliveryManager.loadDeliveryInventory();
        //add details about the suplier name
        deliverBtn.addActionListener(e -> 
            {
                String supplierName = JOptionPane.showInputDialog(
                        this, 
                        "Enter Supplier Name:", 
                        "Supplier Info", 
                        JOptionPane.PLAIN_MESSAGE
                );

                String supplierStaffName = JOptionPane.showInputDialog(
                        this, 
                        "Enter Supplier Staff Name:", 
                        "Supplier Info", 
                        JOptionPane.PLAIN_MESSAGE
                );

                if (supplierName == null || supplierName.trim().isEmpty() || supplierStaffName == null || supplierStaffName.trim().isEmpty()) {
                    JOptionPane.showMessageDialog(
                            this,
                            "Supplier name is required to process delivery.",
                            "Missing Supplier",
                            JOptionPane.WARNING_MESSAGE
                    );
                    return; // stop processing
                }

                //returns if successful or not
                boolean savedDelivery = deliveryManager.saveDeliveries(deliverInventoryTbl, supplierName, supplierStaffName,
                    "data/deliveries.txt", loginUser);
                
                if(!savedDelivery)
                {
                    JOptionPane.showMessageDialog(this, "No items were delivered or an error has occurred", 
                        "Save Failed", JOptionPane.ERROR_MESSAGE);
                    
                        return;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Delivered items successfully saved!",
                        "Save Successful", JOptionPane.INFORMATION_MESSAGE);
                }

                
                //for the next step, create new delivery or view inventory
                int choice = JOptionPane.showOptionDialog(
                    this,
                    "Delivery successfully processed!\nWhat do you want to do next?",
                    "Delivery Processed",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new String[]{"Create New Delivery", "View Inventory"},
                    "Create New Request"
                );
                
                if(choice == 0)
                {   
                    dispose();
                    new GUIDeliveryInventory(loginUser).setVisible(true);
                }
                else if(choice == 1)
                {
                    dispose();
                    new GUIInventory(loginUser).setVisible(true);
                }
            }
        );

        addNewItemBtn.addActionListener(e -> addNewItemAction());
    }


    //move the search item on the top of the table
    private void moveRowToTop(String name) {
        DefaultTableModel model = (DefaultTableModel) deliverInventoryTbl.getModel();

        RowSorter oldSorter = deliverInventoryTbl.getRowSorter();
        deliverInventoryTbl.setRowSorter(null);

        Vector targetRow = null;
        int targetIndex = -1;

        // Find selected row
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 1).toString().equals(name)) { 
                targetRow = (Vector) model.getDataVector().get(i);
                targetIndex = i;
                break;
            }
        }

        if (targetRow == null) return;

        // Remove and reinsert at top
        model.removeRow(targetIndex);
        model.insertRow(0, targetRow);

        deliverInventoryTbl.setRowSorter(oldSorter);

    }

    //apply sorting
    private void applySorting()
    {
        TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) deliverInventoryTbl.getRowSorter();

        String order = orderComboBox.getSelectedItem().toString();

        int columnIndex = 0;

        SortOrder sortOrder = order.equals("Ascending")
            ? SortOrder.ASCENDING : SortOrder.DESCENDING;
        
        List<RowSorter.SortKey> newKeys = new ArrayList<>();
        newKeys.add(new RowSorter.SortKey(columnIndex, sortOrder));

        sorter.setSortKeys(newKeys);
        sorter.sort();
    }

    //show delivered items, variable names is reused
    private void showRequestedItems(JTable table)
    {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        List<Object[]> requestedRows = new ArrayList<>();
        for(int i = 0; i < model.getRowCount(); i ++)
        {
            Object quantityObject = model.getValueAt(i, 4);
            int quantity = 0;
            if(quantityObject instanceof Number)
            {
                quantity = ((Number) quantityObject).intValue();
            }

            if(quantity > 0)
            {
                String itemName = model.getValueAt(i, 1).toString();
                String unit = model.getValueAt(i, 3).toString();
                requestedRows.add(new Object[]{itemName, quantity, unit});
            }
        }

        if(requestedRows.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No items have been requested.", "Requested Items", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        String[] columnNames = {"Item Name", "Quantity", "Unit"};
        Object[][] data = requestedRows.toArray(new Object[0][]);
        JTable requestedTable = new JTable(data, columnNames);
        requestedTable.setEnabled(false);
        requestedTable.setFillsViewportHeight(true);
        requestedTable.setRowHeight(24);

        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                        boolean isSelected, boolean hasFocus,
                                                        int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                setHorizontalAlignment(JLabel.CENTER);
                
                if (!isSelected) {
                    c.setBackground(row % 2 == 1 ? new Color(245,245, 245) : Color.WHITE);
                }

                return c;
            }
        };

        for (int i = 0; i < requestedTable.getColumnCount(); i++) {
            requestedTable.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        JScrollPane scrollPane = new JScrollPane(requestedTable);
        scrollPane.setPreferredSize(new Dimension(300,200));

        JOptionPane.showMessageDialog(this, scrollPane, "Requested Items", JOptionPane.INFORMATION_MESSAGE);
    }

    //add new item with all of the data
    private void addNewItemAction()
    {
        String itemCode = JOptionPane.showInputDialog(this, "Enter Item Code:");
        if(itemCode == null || itemCode.trim().isEmpty()) return;

        String itemName = JOptionPane.showInputDialog(this, "Enter Item Name:");
        if(itemName == null || itemName.trim().isEmpty()) return;

        String qtyStr = JOptionPane.showInputDialog(this, "Enter Initial Quantity:");
        if(qtyStr == null || qtyStr.trim().isEmpty()) return;

        int quantity;
        try {
            quantity = Integer.parseInt(qtyStr);
            if(quantity < 0) {
                JOptionPane.showMessageDialog(this, "Quantity cannot be negative!", 
                                            "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch(NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for quantity!", 
                                        "Invalid Input", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String unit = JOptionPane.showInputDialog(this, "Enter Unit:");
        if(unit == null || unit.trim().isEmpty()) return;

        //Ask for supplier name so the addition is also recorded as a delivery
        String supplierName = JOptionPane.showInputDialog(this, "Enter Supplier Name:");
        if (supplierName == null || supplierName.trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Supplier name is required to record initial delivery.", "Missing Supplier", JOptionPane.WARNING_MESSAGE);
            return;
        }

        //Call the DeliveryManager method to add the new item and record delivery
        DeliveryManager manager = new DeliveryManager(); // or use existing instance
        boolean recorded = manager.addNewItemWithDelivery(itemCode, itemName, quantity, unit, "data/Inventory.txt", requestInventoryPnl, supplierName, "data/deliveries.txt");

        if (!recorded) {
            JOptionPane.showMessageDialog(this, "Failed to record initial delivery. Item may have been added to inventory but delivery was not saved.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        //Refresh table
        manager.loadDeliveryInventory(); // reload items from Inventory.txt
        DefaultTableModel model = (DefaultTableModel) deliverInventoryTbl.getModel();
        model.setRowCount(0); // clear existing rows
        for(Delivery item : manager.getDeliveryItems()) {
            model.addRow(new Object[]{
                item.getItemCode(),
                item.getItemName(),
                item.getQuantity(),
                item.getUnit(),
                0 // initial deliver quantity
            });
        }
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addNewItemBtn;
    private javax.swing.JButton deliverBtn;
    private javax.swing.JTable deliverInventoryTbl;
    private javax.swing.JLabel deliveriesLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel inventoryLbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutLbl;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JPanel requestInventoryPnl;
    private javax.swing.JLabel requestStatusLbl;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JLabel transactionLbl;
    private javax.swing.JButton viewRequestBtn;
    // End of variables declaration//GEN-END:variables
}
