/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;

import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.plaf.FontUIResource;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author USER
 */
public class GUIRequestInventory extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIRequestInventory.class.getName());

    /**
     * Creates new form GUIRequestInventory
     */
    public GUIRequestInventory() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestInventoryPnl = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        requestInventoryTbl = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderComboBox = new javax.swing.JComboBox<>();
        searchTxtField = new javax.swing.JTextField();
        viewRequestBtn = new javax.swing.JButton();
        requestBtn = new javax.swing.JButton();
        homeLbl = new javax.swing.JLabel();
        requestLbl = new javax.swing.JLabel();
        requestStatusLbl = new javax.swing.JLabel();
        logoutLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestInventoryPnl.setBackground(new java.awt.Color(5, 10, 36));

        requestInventoryTbl.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        requestInventoryTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Code", "Item Name", "Quantity", "Unit", "Request Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(requestInventoryTbl);

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Order");

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Search");

        orderComboBox.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        orderComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascending", "Descending" }));
        orderComboBox.addActionListener(this::orderComboBoxActionPerformed);

        searchTxtField.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        searchTxtField.addActionListener(this::searchTxtFieldActionPerformed);

        viewRequestBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        viewRequestBtn.setText("View Request");

        requestBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        requestBtn.setText("Request");

        homeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLbl.setText("Home");

        requestLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestLbl.setText("Request");

        requestStatusLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestStatusLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestStatusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestStatusLbl.setText("Request Status");

        logoutLbl.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logoutLbl.setForeground(new java.awt.Color(255, 255, 255));
        logoutLbl.setText("KOSA");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout requestInventoryPnlLayout = new javax.swing.GroupLayout(requestInventoryPnl);
        requestInventoryPnl.setLayout(requestInventoryPnlLayout);
        requestInventoryPnlLayout.setHorizontalGroup(
            requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(logoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(requestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(requestStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                .addContainerGap(109, Short.MAX_VALUE)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                            .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 767, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                        .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addGap(98, 98, 98))
        );
        requestInventoryPnlLayout.setVerticalGroup(
            requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestInventoryPnlLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(requestStatusLbl)
                            .addComponent(homeLbl)
                            .addComponent(requestLbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestInventoryPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutLbl)
                        .addGap(21, 21, 21)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchTxtField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(orderComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(requestInventoryPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewRequestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(requestBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestInventoryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestInventoryPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchTxtFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTxtFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTxtFieldActionPerformed

    private void orderComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderComboBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIRequestInventory().setVisible(true));
    }


    public GUIRequestInventory(User loginUser)
    {
        initComponents();

        //set labels
        // logout acts as logout button -> open login screen and dispose
        logoutLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        logoutLbl.setToolTipText("Logout");
        logoutLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                GUILogin login = new GUILogin();
                login.setVisible(true);
                dispose();
            }
        });

        //if clicked goes to GUIStaff/HeadDashboard to request items with User parameter
        homeLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        homeLbl.setToolTipText("Go back to Home");
        homeLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homeLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                if(loginUser.getRole().equals("head"))
                {
                    GUIHeadDashboard headDashboard = new GUIHeadDashboard(loginUser);
                    headDashboard.setVisible(true);
                }
                else
                {
                    GUIStaffDashboard staffDashboard = new GUIStaffDashboard(loginUser);
                    staffDashboard.setVisible(true);
                }
                dispose();
            }
        });

        requestLbl.setFont(new Font("Verdana", Font.BOLD, 14));

        //if clicked goes to GUIRequestStatus with User parameter, depending with User role
        requestStatusLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        requestStatusLbl.setToolTipText("View Request Status");
        requestStatusLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        requestStatusLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                if(loginUser.equals("head"))
                {
                    GUIRequestStatus requestStatus = null;
                    try {
                        requestStatus = new GUIRequestStatus(loginUser);
                    } catch (IOException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                    requestStatus.setVisible(true);
                }
                else
                {
                    GUIRequestStatus requestStatus = null;
                    try {
                        requestStatus = new GUIRequestStatus(loginUser);
                    } catch (IOException e) {
                        // TODO Auto-generated catch block
                        e.printStackTrace();
                    }
                    requestStatus.setVisible(true);
                }
                dispose();
            }
        });
        

        //instantiate ItemsManager to get its methods
        ItemsManager itemsManager = new ItemsManager();
        itemsManager.loadInventory();
        List<Items> itemList = itemsManager.getItems();

        //get the model of the table to edit its column, for sorting, and overall look
        DefaultTableModel model = (DefaultTableModel) requestInventoryTbl.getModel();
        model.setRowCount(0);

        //fill the table's viewport heaight, and set each row height row 
        requestInventoryTbl.setFillsViewportHeight(true);
        requestInventoryTbl.setRowHeight(24);

        //declare a DefaultTableCellRenderer to have a alternating color for the rows
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                        boolean isSelected, boolean hasFocus,
                                                        int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                setHorizontalAlignment(JLabel.CENTER);
                
                if (!isSelected) {
                    c.setBackground(row % 2 == 1 ? new Color(245,245, 245) : Color.WHITE);
                }

                return c;
            }
        };

        for (int i = 0; i < requestInventoryTbl.getColumnCount(); i++) {
            requestInventoryTbl.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        //add to the model table the itemCode, itemName, quantity, and its unit
        for(Items item : itemsManager.getItems())
        {
            model.addRow(new Object[]
                {
                    item.getItemCode(),
                    item.getItemName(),
                    item.getQuantity(),
                    item.getUnit(),
                    null
                }
            );
        }

        //declare a JPopupMenu for the search feature
        JPopupMenu popup = new JPopupMenu();
        popup.setFocusable(false);

        //JList for the suggestionList, and JScrollPane for the dropdown of suggestionList
        JList<String> suggestionList = new JList<>();
        JScrollPane scrollPane = new JScrollPane(suggestionList);
        scrollPane.setPreferredSize(new Dimension(searchTxtField.getWidth(), 100));
        popup.add(scrollPane);

        //to function the search text field
        searchTxtField.getDocument().addDocumentListener(new DocumentListener() {
            public void update()
            {
                //get the text from the searchTxtField
                String text = searchTxtField.getText().toLowerCase();
                DefaultListModel<String> model = new DefaultListModel<>();

                //to get the items that matches with the searched text
                for (Items item : itemList) {
                    if (item.getItemName().toLowerCase().contains(text) && !text.isEmpty()) {
                        model.addElement(item.getItemName());
                    }
                }
                suggestionList.setModel(model);

                if (!model.isEmpty()) {
                    popup.show(searchTxtField, 0, searchTxtField.getHeight());
                } else {
                    popup.setVisible(false);
                }
            }
            @Override
            public void insertUpdate(DocumentEvent e) { update(); }
            @Override
            public void removeUpdate(DocumentEvent e) { update(); }
            @Override
            public void changedUpdate(DocumentEvent e) { update(); }
        });

        //once the suggestion from the suggestionList is clicked
        suggestionList.addMouseListener((new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e)
            {
                //to move the selectedName to the top of the table
                String selectedName = suggestionList.getSelectedValue();
                if(selectedName == null) return;

                searchTxtField.setText(selectedName);
                popup.setVisible(false);

                moveRowToTop(selectedName);
            }
        }));

        //to sort the table based on the selected parameter
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(requestInventoryTbl.getModel());
        requestInventoryTbl.setRowSorter(sorter);

        //to applySorting
        orderComboBox.addActionListener(e -> applySorting());

        //for the spinner, in the quantity row
        requestInventoryTbl.getColumnModel().getColumn(4).setCellEditor(new SpinnerEditor(false));

        //to show the requested items
        viewRequestBtn.addActionListener(e -> showRequestedItems(requestInventoryTbl));

        //to process the request
        RequestManager requestManager = new RequestManager();
        requestBtn.addActionListener(e -> 
            {
                //gets if the saving is successful
                boolean savedRequest = requestManager.saveRequests(requestInventoryTbl, loginUser.getDepartment(), 
                    loginUser.getRole(), loginUser.getFilePath(), loginUser);
                
                if(!savedRequest)
                {
                    JOptionPane.showMessageDialog(this, "No items were requested or an error has occurred", 
                        "Save Failed", JOptionPane.ERROR_MESSAGE);
                    
                        return;
                }
                else
                {
                    JOptionPane.showMessageDialog(this, "Requested items successfully saved!",
                        "Save Successful", JOptionPane.INFORMATION_MESSAGE);
                }

                
                //next step by the user, if the user want to create new request or view request status
                int choice = JOptionPane.showOptionDialog(
                    this,
                    "Request successfully created!",
                    "Request Created",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE,
                    null,
                    new String[]{"Create New Request", "View Request Status"},
                    "Create New Request"
                );
                
                //if zero goes to GUIRequestInventory
                if(choice == 0)
                {   
                    dispose();
                    new GUIRequestInventory(loginUser).setVisible(true);
                }
                //if one goes to GUIRequestStatus
                else if(choice == 1)
                {
                    dispose();
                    try {
                        new GUIRequestStatus(loginUser).setVisible(true);
                    } catch (IOException e1) {
                        // TODO Auto-generated catch block
                        e1.printStackTrace();
                    }
                }
            }
        );
    }

    //to move the selected items and its data to the top of the table
    private void moveRowToTop(String name) {
        DefaultTableModel model = (DefaultTableModel) requestInventoryTbl.getModel();

        RowSorter oldSorter = requestInventoryTbl.getRowSorter();
        requestInventoryTbl.setRowSorter(null);

        Vector targetRow = null;
        int targetIndex = -1;

        // Find selected row
        for (int i = 0; i < model.getRowCount(); i++) {
            if (model.getValueAt(i, 1).toString().equals(name)) { 
                targetRow = (Vector) model.getDataVector().get(i);
                targetIndex = i;
                break;
            }
        }

        if (targetRow == null) return;

        // Remove and reinsert at top
        model.removeRow(targetIndex);
        model.insertRow(0, targetRow);

        requestInventoryTbl.setRowSorter(oldSorter);

    }

    //to apply the sorting
    private void applySorting()
    {
        TableRowSorter<TableModel> sorter = (TableRowSorter<TableModel>) requestInventoryTbl.getRowSorter();

        String order = orderComboBox.getSelectedItem().toString();

        int columnIndex = 0;

        //if ascending or descending using SortOrder
        SortOrder sortOrder = order.equals("Ascending")
            ? SortOrder.ASCENDING : SortOrder.DESCENDING;
        
        List<RowSorter.SortKey> newKeys = new ArrayList<>();
        newKeys.add(new RowSorter.SortKey(columnIndex, sortOrder));

        sorter.setSortKeys(newKeys);
        sorter.sort();
    }

    //showReqeustedItems based on the input quantity/ies of the user
    private void showRequestedItems(JTable table)
    {
        DefaultTableModel model = (DefaultTableModel) table.getModel();

        //List of requested Rows
        List<Object[]> requestedRows = new ArrayList<>();
        for(int i = 0; i < model.getRowCount(); i ++)
        {
            //check if object in the cell is a number
            Object quantityObject = model.getValueAt(i, 4);
            int quantity = 0;
            if(quantityObject instanceof Number)
            {
                quantity = ((Number) quantityObject).intValue();
            }

            //if quantity > 0, get the itemName and its unit
            if(quantity > 0)
            {
                String itemName = model.getValueAt(i, 1).toString();
                String unit = model.getValueAt(i, 3).toString();
                requestedRows.add(new Object[]{itemName, quantity, unit});
            }
        }

        //catch if requestedrows is empty
        if(requestedRows.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No items have been requested.", "Requested Items", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //set the table of requested items that will be displayed in the JOptionPane of requested Items
        String[] columnNames = {"Item Name", "Quantity", "Unit"};
        Object[][] data = requestedRows.toArray(new Object[0][]);
        JTable requestedTable = new JTable(data, columnNames);
        requestedTable.setEnabled(false);
        requestedTable.setFillsViewportHeight(true);
        requestedTable.setRowHeight(24);

        //alternating colors of rows
        DefaultTableCellRenderer renderer = new DefaultTableCellRenderer() {
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value,
                                                        boolean isSelected, boolean hasFocus,
                                                        int row, int column) {
                Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);

                setHorizontalAlignment(JLabel.CENTER);
                
                if (!isSelected) {
                    c.setBackground(row % 2 == 1 ? new Color(245,245, 245) : Color.WHITE);
                }

                return c;
            }
        };

        for (int i = 0; i < requestedTable.getColumnCount(); i++) {
            requestedTable.getColumnModel().getColumn(i).setCellRenderer(renderer);
        }

        JScrollPane scrollPane = new JScrollPane(requestedTable);
        scrollPane.setPreferredSize(new Dimension(300,200));

        JOptionPane.showMessageDialog(this, scrollPane, "Requested Items", JOptionPane.INFORMATION_MESSAGE);
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutLbl;
    private javax.swing.JComboBox<String> orderComboBox;
    private javax.swing.JButton requestBtn;
    private javax.swing.JPanel requestInventoryPnl;
    private javax.swing.JTable requestInventoryTbl;
    private javax.swing.JLabel requestLbl;
    private javax.swing.JLabel requestStatusLbl;
    private javax.swing.JTextField searchTxtField;
    private javax.swing.JButton viewRequestBtn;
    // End of variables declaration//GEN-END:variables
}
