/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class GUIRequestStatusForAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIRequestStatusForAdmin.class.getName());

    /**
     * Creates new form GUIRequestStatus
     */
    public GUIRequestStatusForAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestStatusPnl = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        createRequestLbl = new javax.swing.JLabel();
        requestStatusLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        requestsTabbedPane = new javax.swing.JTabbedPane();
        deliveriesLbl = new javax.swing.JLabel();
        transactionsLbl = new javax.swing.JLabel();
        logoutLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestStatusPnl.setBackground(new java.awt.Color(5, 10, 36));
        requestStatusPnl.setForeground(new java.awt.Color(255, 255, 255));

        homeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLbl.setText("Home");

        createRequestLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        createRequestLbl.setForeground(new java.awt.Color(255, 255, 255));
        createRequestLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        requestStatusLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestStatusLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestStatusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestStatusLbl.setText("Requests");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        requestsTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        deliveriesLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        deliveriesLbl.setForeground(new java.awt.Color(255, 255, 255));
        deliveriesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveriesLbl.setText("Deliveries");

        transactionsLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        transactionsLbl.setForeground(new java.awt.Color(255, 255, 255));
        transactionsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionsLbl.setText("Transactions");

        logoutLbl.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logoutLbl.setForeground(new java.awt.Color(255, 255, 255));
        logoutLbl.setText("KOSA");

        javax.swing.GroupLayout requestStatusPnlLayout = new javax.swing.GroupLayout(requestStatusPnl);
        requestStatusPnl.setLayout(requestStatusPnlLayout);
        requestStatusPnlLayout.setHorizontalGroup(
            requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestStatusPnlLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(logoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(createRequestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestStatusLbl)
                .addGap(27, 27, 27)
                .addComponent(deliveriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(transactionsLbl)
                .addGap(36, 36, 36))
            .addGroup(requestStatusPnlLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(requestsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 822, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        requestStatusPnlLayout.setVerticalGroup(
            requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestStatusPnlLayout.createSequentialGroup()
                .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestStatusPnlLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(createRequestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(homeLbl)
                            .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(requestStatusLbl)
                                .addComponent(deliveriesLbl)
                                .addComponent(transactionsLbl)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestStatusPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logoutLbl)
                        .addGap(23, 23, 23)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestStatusPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestStatusPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIRequestStatusForAdmin().setVisible(true));
    }

    private Map<String, List<Request>> requestsMap;   // <-- CLASS FIELD

    public GUIRequestStatusForAdmin(User loginUser) throws IOException
    {
        initComponents();

        //set the labels
        setLbl(loginUser);

        //hash map of the dept with its dept txt file
        Map<String, String> deptFiles = new HashMap<>();

        if(loginUser.getRole().equalsIgnoreCase("admin"))
        {
            deptFiles.put("Engineering", "data/engineering_dept_requests.txt");
            deptFiles.put("Financial", "data/financial_dept_requests.txt");
            deptFiles.put("HR","data/human_resource_dept_requests.txt");
            deptFiles.put("IT", "data/it_dept_requests.txt");
            deptFiles.put("Logistics", "data/logistics_dept_requests.txt");
            deptFiles.put("LCC Ayala", "data/lcc_ayala_branch_requests.txt");
            deptFiles.put("LCC Daraga", "data/lcc_daraga_branch_requests.txt");   

            //for the department, to display the RequestStatusPanel
            for(String dept : deptFiles.keySet())
            {
                String filePath = deptFiles.get(dept);
                RequestStatusPanel statusPanel = new RequestStatusPanel(loginUser, dept, filePath, requestStatusPnl, TransactionType.REQUEST);
                requestsTabbedPane.addTab(dept, statusPanel);
            }
        }
        else
        {
            //set the tabbedpane for the request status
            requestsTabbedPane.setVisible(false);
            RequestStatusPanel statusPanel = new RequestStatusPanel(loginUser,loginUser.getDepartment(), loginUser.getFilePath(), requestStatusPnl, TransactionType.REQUEST);
            requestStatusPnl.setLayout(new BorderLayout());
            statusPanel.setBorder(BorderFactory.createEmptyBorder(100, 50, 0, 0));
            requestStatusPnl.setLayout(new BorderLayout());
            requestStatusPnl.add(statusPanel, BorderLayout.CENTER);

            requestStatusPnl.revalidate();
            requestStatusPnl.repaint();
        }

    }

    //set labels
    private void setLbl(User loginUser)
    {
        // logout acts like a logout button
        logoutLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        logoutLbl.setToolTipText("Logout");
        logoutLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt) {
                GUILogin login = new GUILogin();
                login.setVisible(true);
                dispose();
            }
        });

        //label for home, to go back to home depending on the loginUser
        homeLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        homeLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homeLbl.setToolTipText("Go back Home");
        homeLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                if(loginUser.getRole().equals("head"))
                {
                    GUIHeadDashboard headDashboard = new GUIHeadDashboard(loginUser);
                    headDashboard.setVisible(true);
                }
                else if(loginUser.getRole().equals("staff"))
                {
                    GUIStaffDashboard staffDashboard = new GUIStaffDashboard(loginUser);
                    staffDashboard.setVisible(true);
                }
                else if(loginUser.getRole().equals("admin"))
                {
                    GUIAdminDashboard adminDashboard = new GUIAdminDashboard(loginUser);
                    adminDashboard.setVisible(true);
                }
                dispose();
            }
        });

        //label for createRequest to go back to create request according to loginUser
        createRequestLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        createRequestLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));

        if(loginUser.getRole().equals("head") || loginUser.getRole().equals("staff"))
        {
            createRequestLbl.setText("Request");
            createRequestLbl.setToolTipText("Create New Request");
            createRequestLbl.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent evt)
                {
                    GUIRequestInventory requestInventory = new GUIRequestInventory(loginUser);
                    requestInventory.setVisible(true);
                    dispose();
                }
            });
        }
        else if(loginUser.getRole().equals("admin"))
        {
            createRequestLbl.setText("Inventory");
            createRequestLbl.setToolTipText("View Inventory");
            createRequestLbl.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent evt)
                {
                    GUIInventory inventory = new GUIInventory(loginUser);
                    inventory.setVisible(true);
                    dispose();
                }
            });
        }

        requestStatusLbl.setFont(new Font("Verdana", Font.BOLD, 12));

        //for the deliveries
        deliveriesLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        deliveriesLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        deliveriesLbl.setToolTipText("View Requests of Departments");
        deliveriesLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUIDeliveryInventory deliveryInventory = new GUIDeliveryInventory(loginUser);
                deliveryInventory.setVisible(true);
                dispose();
            }
        });

        //and to the transactions
        transactionsLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        transactionsLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        transactionsLbl.setToolTipText("View All Transactions");
        transactionsLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                GUITransactions transactions;
                try {
                    transactions = new GUITransactions(loginUser);
                    transactions.setVisible(true);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                dispose();
            }
        });
    }

    //to add department tab, in the tabbedpane
    public void addDepartmentTab(String dept, RequestStatusPanel panel)
    {
        requestsTabbedPane.addTab(dept, panel);
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createRequestLbl;
    private javax.swing.JLabel deliveriesLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutLbl;
    private javax.swing.JLabel requestStatusLbl;
    private javax.swing.JPanel requestStatusPnl;
    private javax.swing.JTabbedPane requestsTabbedPane;
    private javax.swing.JLabel transactionsLbl;
    // End of variables declaration//GEN-END:variables
}
