/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.BorderLayout;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.swing.BorderFactory;
import javax.swing.JPanel;
import javax.swing.border.Border;

/**
 *
 * @author USER
 */
public class GUIRequestStatus extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIRequestStatus.class.getName());

    /**
     * Creates new form GUIRequestStatus
     */
    public GUIRequestStatus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        requestStatusPnl = new javax.swing.JPanel();
        homeLbl = new javax.swing.JLabel();
        createRequestLbl = new javax.swing.JLabel();
        requestStatusLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        requestsTabbedPane = new javax.swing.JTabbedPane();
        homeLbl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        requestStatusPnl.setBackground(new java.awt.Color(5, 10, 36));

        homeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setText("Home");

        createRequestLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        createRequestLbl.setForeground(new java.awt.Color(255, 255, 255));
        createRequestLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        requestStatusLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestStatusLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestStatusLbl.setText("Request Status");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        requestsTabbedPane.setBackground(new java.awt.Color(255, 255, 255));

        homeLbl1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        homeLbl1.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl1.setText("KOSA");

        javax.swing.GroupLayout requestStatusPnlLayout = new javax.swing.GroupLayout(requestStatusPnl);
        requestStatusPnl.setLayout(requestStatusPnlLayout);
        requestStatusPnlLayout.setHorizontalGroup(
            requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestStatusPnlLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(homeLbl1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(createRequestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(requestStatusPnlLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(requestsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        requestStatusPnlLayout.setVerticalGroup(
            requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(requestStatusPnlLayout.createSequentialGroup()
                .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(requestStatusPnlLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(requestStatusPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(homeLbl)
                                .addComponent(requestStatusLbl))
                            .addComponent(createRequestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, requestStatusPnlLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(homeLbl1)
                        .addGap(20, 20, 20)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestStatusPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(requestStatusPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIRequestStatus().setVisible(true));
    }

    private Map<String, List<Request>> requestsMap;   // <-- CLASS FIELD

    public GUIRequestStatus(User loginUser) throws IOException
    {
        initComponents();

        setLbl(loginUser);

        Map<String, String> deptFiles = new HashMap<>();

        if(loginUser.getRole().equalsIgnoreCase("admin"))
        {
            deptFiles.put("Engineering", "data/engineering_dept_requests.txt");
            deptFiles.put("Financial", "data/financial_dept_requests.txt");
            deptFiles.put("HR","data/human_resource_dept_requests.txt");
            deptFiles.put("IT", "data/it_dept_requests.txt");
            deptFiles.put("Logistics", "data/logistics_dept_requests.txt");
            deptFiles.put("LCC Ayala", "data/lcc_ayala_branch_requests.txt");
            deptFiles.put("LCC Daraga", "data/lcc_daraga_branch_requests.txt");   

            for(String dept : deptFiles.keySet())
            {
                String filePath = deptFiles.get(dept);
                RequestStatusPanel statusPanel = new RequestStatusPanel(loginUser, dept, filePath, requestStatusPnl, TransactionType.REQUEST);
                requestsTabbedPane.addTab(dept, statusPanel);
            }
        }
        else{
            requestsTabbedPane.setVisible(false);
            RequestStatusPanel statusPanel = new RequestStatusPanel(loginUser,loginUser.getDepartment(), loginUser.getFilePath(), requestStatusPnl, TransactionType.REQUEST);
            requestStatusPnl.setLayout(new BorderLayout());
            statusPanel.setBorder(BorderFactory.createEmptyBorder(100, 95, 0, 0));
            requestStatusPnl.setLayout(new BorderLayout());
            requestStatusPnl.add(statusPanel, BorderLayout.CENTER);

            requestStatusPnl.revalidate();
            requestStatusPnl.repaint();
        }

    }




    private void setLbl(User loginUser)
    {
        homeLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        homeLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homeLbl.setToolTipText("Go back Home");
        homeLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(MouseEvent evt)
            {
                if(loginUser.getRole().equals("head"))
                {
                    GUIHeadDashboard headDashboard = new GUIHeadDashboard(loginUser);
                    headDashboard.setVisible(true);
                }
                else if(loginUser.getRole().equals("staff"))
                {
                    GUIStaffDashboard staffDashboard = new GUIStaffDashboard(loginUser);
                    staffDashboard.setVisible(true);
                }
                else if(loginUser.getRole().equals("admin"))
                {
                    GUIAdminDashboard adminDashboard = new GUIAdminDashboard(loginUser);
                    adminDashboard.setVisible(true);
                }
                dispose();
            }
        });

        createRequestLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        createRequestLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));

        if(loginUser.getRole().equals("head") || loginUser.getRole().equals("staff"))
        {
            createRequestLbl.setText("Request");
            createRequestLbl.setToolTipText("Create New Request");
            createRequestLbl.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent evt)
                {
                    GUIRequestInventory requestInventory = new GUIRequestInventory(loginUser);
                    requestInventory.setVisible(true);
                    dispose();
                }
            });
        }
        else if(loginUser.getRole().equals("admin"))
        {
            createRequestLbl.setText("Inventory");
            createRequestLbl.setToolTipText("View Inventory");
            createRequestLbl.addMouseListener(new MouseAdapter() {
                public void mouseClicked(MouseEvent evt)
                {
                    GUIInventory inventory = new GUIInventory(loginUser);
                    inventory.setVisible(true);
                    dispose();
                }
            });
        }

        requestStatusLbl.setFont(new Font("Verdana", Font.BOLD, 14));

        
    }

    public void addDepartmentTab(String dept, RequestStatusPanel panel)
    {
        requestsTabbedPane.addTab(dept, panel);
    }

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel createRequestLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel homeLbl1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel requestStatusLbl;
    private javax.swing.JPanel requestStatusPnl;
    private javax.swing.JTabbedPane requestsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
