/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;

/**
 *
 * @author USER
 */
public class GUIStaffDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIStaffDashboard.class.getName());

    /**
     * Creates new form GUIStaffDashboard
     */
    public GUIStaffDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        staffDashboardPnl = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        homeLbl = new javax.swing.JLabel();
        requestLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        welcomeLbl = new javax.swing.JLabel();
        toKosaLbl = new javax.swing.JLabel();
        descriptionLbl = new javax.swing.JLabel();
        requestStatusLbl = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        staffDashboardPnl.setBackground(new java.awt.Color(5, 10, 36));
        staffDashboardPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                staffDashboardPnlMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KOSA");

        homeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLbl.setText("Home");

        requestLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestLbl.setText("Request");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        welcomeLbl.setForeground(new java.awt.Color(255, 255, 255));
        welcomeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLbl.setText("jLabel2");

        toKosaLbl.setForeground(new java.awt.Color(255, 255, 255));
        toKosaLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toKosaLbl.setText("jLabel3");

        descriptionLbl.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLbl.setText("jLabel4");

        requestStatusLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestStatusLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestStatusLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestStatusLbl.setText("Request Status");
        requestStatusLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                requestStatusLblMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("About Us");

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contact ");

        javax.swing.GroupLayout staffDashboardPnlLayout = new javax.swing.GroupLayout(staffDashboardPnl);
        staffDashboardPnl.setLayout(staffDashboardPnlLayout);
        staffDashboardPnlLayout.setHorizontalGroup(
            staffDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, staffDashboardPnlLayout.createSequentialGroup()
                .addGap(26, 531, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestStatusLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(staffDashboardPnlLayout.createSequentialGroup()
                .addGroup(staffDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(staffDashboardPnlLayout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addGroup(staffDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(welcomeLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(staffDashboardPnlLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(descriptionLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(toKosaLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(staffDashboardPnlLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        staffDashboardPnlLayout.setVerticalGroup(
            staffDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(staffDashboardPnlLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(1, 1, 1)
                .addGroup(staffDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(homeLbl)
                    .addComponent(requestLbl)
                    .addComponent(requestStatusLbl))
                .addGap(8, 8, 8)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(welcomeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toKosaLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addGroup(staffDashboardPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(53, 53, 53))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffDashboardPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(staffDashboardPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void staffDashboardPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_staffDashboardPnlMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_staffDashboardPnlMouseClicked

    private void requestStatusLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_requestStatusLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_requestStatusLblMouseClicked

    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUIStaffDashboard().setVisible(true));
    }

    public GUIStaffDashboard(User loginUser)
    {
        initComponents();

        homeLbl.setFont(new Font("Alexandria", Font.BOLD, 14));

        requestLbl.setFont(new Font("Alexandria", Font.PLAIN, 14));
        requestLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        requestLbl.setToolTipText("Create a Request");
        requestLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt)
            {
                GUIRequestInventory requestForm = new GUIRequestInventory(loginUser);
                requestForm.setVisible(true);
                dispose();
            }
        });
        requestStatusLbl.setFont(new Font("Alexandria", Font.PLAIN, 14));
        requestStatusLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        requestStatusLbl.setToolTipText("View Request Status");
        requestStatusLbl.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent evt)
            {
                GUIRequestStatus requestStatus;
                try {
                    requestStatus = new GUIRequestStatus(loginUser);
                    requestStatus.setVisible(true);
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }
                
                dispose();
            }
        });

        setWelcomeLbls();
    }
    private void setWelcomeLbls()
    {
        welcomeLbl.setText("Welcome");
        welcomeLbl.setFont(new Font("Verdana", Font.BOLD, 40));

        toKosaLbl.setText("to KOSA");
        toKosaLbl.setFont(new Font("Verdana", Font.BOLD, 20));

        String text = "<html>" + 
            "<center>Our centralized platform for efficiently managing and tracking<br>" + 
            "all office supplies. With KOSA, we can easily monitor inventory<br>" + 
            "levels, process staff requests, and ensure that every item is <br>" + 
            "issued accurately and on time. This system helps us stay<br>" + 
            "organized, maintain accountability, and support smooth<br>" +
            "operations across all departments.</center>" + "</html>";

        descriptionLbl.setText(text);
        descriptionLbl.setFont(new Font("Verdana", Font.PLAIN, 12));
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel requestLbl;
    private javax.swing.JLabel requestStatusLbl;
    private javax.swing.JPanel staffDashboardPnl;
    private javax.swing.JLabel toKosaLbl;
    private javax.swing.JLabel welcomeLbl;
    // End of variables declaration//GEN-END:variables
}
