/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

import com.mycompany.managers.*;
import com.mycompany.auxiliary.*;
import com.mycompany.models.*;
import com.mycompany.gui.*;

import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.util.List;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;

import org.w3c.dom.events.MouseEvent;

/**
 *
 * @author USER
 */
public class GUITransactions extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUITransactions.class.getName());

    /**
     * Creates new form GUITransactions
     */
    public GUITransactions() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transactionsPnl = new javax.swing.JPanel();
        transactionsTabbedPane = new javax.swing.JTabbedPane();
        requestsTabbedPane = new javax.swing.JTabbedPane();
        logoutLbl = new javax.swing.JLabel();
        homeLbl = new javax.swing.JLabel();
        inventoryLbl = new javax.swing.JLabel();
        requestsLbl = new javax.swing.JLabel();
        deliveriesLbl = new javax.swing.JLabel();
        transactionsLbl = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        saveReceiptBtn = new javax.swing.JButton();
        saveReportBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        transactionsPnl.setBackground(new java.awt.Color(5, 10, 36));
        transactionsPnl.setForeground(new java.awt.Color(255, 255, 255));

        transactionsTabbedPane.addTab("tab1", requestsTabbedPane);

        logoutLbl.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        logoutLbl.setForeground(new java.awt.Color(255, 255, 255));
        logoutLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutLbl.setText("KOSA");

        homeLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        homeLbl.setForeground(new java.awt.Color(255, 255, 255));
        homeLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeLbl.setText("Home");

        inventoryLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        inventoryLbl.setForeground(new java.awt.Color(255, 255, 255));
        inventoryLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        inventoryLbl.setText("Inventory");

        requestsLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        requestsLbl.setForeground(new java.awt.Color(255, 255, 255));
        requestsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        requestsLbl.setText("Requests");

        deliveriesLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        deliveriesLbl.setForeground(new java.awt.Color(255, 255, 255));
        deliveriesLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deliveriesLbl.setText("Deliveries");

        transactionsLbl.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        transactionsLbl.setForeground(new java.awt.Color(255, 255, 255));
        transactionsLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        transactionsLbl.setText("Transactions");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        saveReceiptBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        saveReceiptBtn.setText("Receipt");

        saveReportBtn.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        saveReportBtn.setText("Report");
        saveReportBtn.addActionListener(this::saveReportBtnActionPerformed);

        javax.swing.GroupLayout transactionsPnlLayout = new javax.swing.GroupLayout(transactionsPnl);
        transactionsPnl.setLayout(transactionsPnlLayout);
        transactionsPnlLayout.setHorizontalGroup(
            transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(homeLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inventoryLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(requestsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deliveriesLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transactionsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
            .addComponent(jSeparator1)
            .addGroup(transactionsPnlLayout.createSequentialGroup()
                .addGroup(transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionsPnlLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logoutLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(transactionsPnlLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(transactionsTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 873, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(saveReceiptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(saveReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        transactionsPnlLayout.setVerticalGroup(
            transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactionsPnlLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(logoutLbl)
                .addGroup(transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(transactionsPnlLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(transactionsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(transactionsLbl)
                            .addComponent(deliveriesLbl)
                            .addComponent(requestsLbl)
                            .addComponent(inventoryLbl)
                            .addComponent(homeLbl))
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(transactionsTabbedPane))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transactionsPnlLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 490, Short.MAX_VALUE)
                        .addComponent(saveReportBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(saveReceiptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transactionsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(transactionsPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveReportBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveReportBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveReportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GUITransactions().setVisible(true));
    }

    private User loginUser;
    private TransactionManager transactionManager;

    public GUITransactions(User loginUser) throws IOException
    {
        this.loginUser = loginUser;
        initComponents();

        //set labels
        // logout returns to login screen
        logoutLbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutLbl.setToolTipText("Logout");
        logoutLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GUILogin login = new GUILogin();
                login.setVisible(true);
                dispose();
            }
        });
        homeLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        homeLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        homeLbl.setToolTipText("Go back Home");
        homeLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                if(loginUser.getRole().equals("head"))
                {
                    GUIHeadDashboard headDashboard = new GUIHeadDashboard(loginUser);
                    headDashboard.setVisible(true);
                }
                else if(loginUser.getRole().equals("staff"))
                {
                    GUIStaffDashboard staffDashboard = new GUIStaffDashboard(loginUser);
                    staffDashboard.setVisible(true);
                }
                else if(loginUser.getRole().equals("admin"))
                {
                    GUIAdminDashboard adminDashboard = new GUIAdminDashboard(loginUser);
                    adminDashboard.setVisible(true);
                }
                dispose();
            }
        });
        inventoryLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        inventoryLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        inventoryLbl.setToolTipText("Go to Inventory");
        inventoryLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                GUIInventory inventoryForm = new GUIInventory(loginUser);
                inventoryForm.setVisible(true);
                dispose();
            }
        });

        requestsLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        requestsLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        requestsLbl.setToolTipText("View Requests of Departments");
        requestsLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                try {
                    GUIRequestStatusForAdmin requestStatus = new GUIRequestStatusForAdmin(loginUser);
                    requestStatus.setVisible(true);
                    dispose();
                } catch (IOException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

                dispose();
            }
        });
        
        deliveriesLbl.setFont(new Font("Verdana", Font.PLAIN, 14));
        deliveriesLbl.setCursor(new Cursor(Cursor.HAND_CURSOR));
        deliveriesLbl.setToolTipText("View Requests of Departments");
        deliveriesLbl.addMouseListener(new MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                GUIDeliveryInventory deliveryInventory = new GUIDeliveryInventory(loginUser);
                deliveryInventory.setVisible(true);
                dispose();
            }
        });
        transactionsLbl.setFont(new Font("Verdana", Font.BOLD, 14));

        //load al transactions
        transactionManager = new TransactionManager();
        List<Transaction> transactions = transactionManager.loadAllTransactions();

        //setup the tabs in the tabbed pane, requests and deliveries
        setupRequestTabs(transactions);
        setupDeliveryTab(transactions);

        //to save the receipts
        saveReceiptBtn.addActionListener(e -> {
            try {
                saveReceipt();
            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(GUITransactions.this, "Failed to save receipt: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        });

        //to save the report
        saveReportBtn.addActionListener(e -> {
            try {
                saveReport();
            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(GUITransactions.this, "Failed to save report: " + ex.getMessage(), "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            }
        });
    }

    //save report
    private void saveReport() throws IOException {
        Component sel = transactionsTabbedPane.getSelectedComponent();

        TransactionPanel panel = null;
        if (sel instanceof JTabbedPane) {
            JTabbedPane tabs = (JTabbedPane) sel;
            Component comp = tabs.getSelectedComponent();
            if (comp instanceof TransactionPanel) panel = (TransactionPanel) comp;
        } else if (sel instanceof TransactionPanel) {
            panel = (TransactionPanel) sel;
        }

        if (panel == null) {
            JOptionPane.showMessageDialog(this, "No transaction panel selected.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //get all transactions to declare in a List<Transactions>
        List<Transaction> all = panel.getAllTransactions();
        if (all.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No transactions available for report.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //determine latest date among the panel's transactions (use dateCreated)
        LocalDate latest = null;
        for (Transaction t : all) {
            if (t.getDateCreated() == null) continue;
            if (latest == null || t.getDateCreated().isAfter(latest)) latest = t.getDateCreated();
        }

        if (latest == null) {
            JOptionPane.showMessageDialog(this, "Transactions have no dates to base the report on.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        LocalDate start = latest.minusDays(5);

        //to set the report to be in a 5 days span
        List<Transaction> inRange = new java.util.ArrayList<>();
        for (Transaction t : all) {
            LocalDate d = t.getDateCreated();
            if (d == null) continue;
            if ((d.isAfter(start) || d.isEqual(start)) && (d.isBefore(latest) || d.isEqual(latest))) {
                inRange.add(t);
            }
        }

        if (inRange.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No transactions found in the 5-day window.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        File reportsDir = new File("data/Reports");
        if (!reportsDir.exists()) reportsDir.mkdirs();

        //to set the file name of the txt file
        String typeLabel = panel.getTransactionType() == TransactionType.DELIVERY ? "Delivery" : "Request";
        String source = panel.getSourceName() == null ? "Unknown" : panel.getSourceName().replaceAll("\\s+", "_");
        String fileName = "Weekly_Report_" + typeLabel + "_" + source + "_" + latest.toString() + ".txt";
        File out = new File(reportsDir, fileName);

        //write the report txt file
        //format the txt file
        try (BufferedWriter bw = new BufferedWriter(new java.io.FileWriter(out))) {
            bw.write(typeLabel + " Weekly Report\n");
            bw.write("Source: " + panel.getSourceName() + "\n");
            bw.write("Date Range: " + start.toString() + " to " + latest.toString() + "\n");
            bw.write("------------------------------------------------------------\n");

            if (panel.getTransactionType() == TransactionType.REQUEST) {
                bw.write(String.format("%-17s %-17s %-17s %-12s %-30s %-8s %-12s %-8s %-20s %-12s %-12s %12s\n",
                    "RequestID","Requested By","Released By","Item Code","Item Name","Quantity","To Release","Unit","Status","Date Created", "Date Approved", "Date Released"));
                for (Transaction t : inRange) {
                    bw.write(String.format("%-17s %-17s %-17s %-12s %-30s %-8d %-12d %-8s %-20s %-12s %-12s %12s\n",
                        t.getTransactionId(), 
                        t.getUserName(),
                        (t.getReleasedOrDeliveredBy()==null?"" : t.getReleasedOrDeliveredBy()), 
                        t.getItemCode(), 
                        t.getItemName(), 
                        t.getQuantity(),
                        t.getQuantityToBeReleased(), 
                        t.getUnit(), 
                        (t.getStatus()==null ? "" : t.getStatus()), 
                        (t.getDateCreated()==null?"" : t.getDateCreated().toString()), 
                        (t.getDateApproved()==null ? "" : t.getDateApproved().toString()), 
                        (t.getDateCompleted()==null ? "" : t.getDateCreated().toString().trim())));
                }
                bw.newLine();
                bw.newLine();   
                bw.write("Prepared By: " + loginUser.getUsername());
            } else {
                bw.write(String.format("%-17s %-17s %-17s %-12s %-30s %-8s %-8s %-12s %12s\n",
                    "DeliveryID","Delivered By","Received By","Item Code","Item Name","Quantity","Unit","Date Created", "Date Received"));
                for (Transaction t : inRange) {
                    bw.write(String.format("%-17s %-17s %-17s %-12s %-30s %-8d %-8s %-12s %12s\n",
                        t.getTransactionId(), 
                        t.getReleasedOrDeliveredBy(),
                        t.getUserName(),
                        t.getItemCode(), 
                        t.getItemName(), 
                        t.getQuantity(), 
                        t.getUnit(), 
                        (t.getDateCreated()==null ? "" : t.getDateCreated().toString()), 
                        (t.getDateCompleted()==null ? "" : t.getDateCreated().toString().trim())));
                }
                bw.newLine();
                bw.newLine();   
                bw.write("Prepared By: " + loginUser.getUsername());
            }

            bw.flush();
        }

        JOptionPane.showMessageDialog(this, "Report saved to: " + out.getAbsolutePath(), "Saved", JOptionPane.INFORMATION_MESSAGE);
    }

    //save the receipt of transaction, delivery/request
    private void saveReceipt() throws IOException {
        Component sel = transactionsTabbedPane.getSelectedComponent();

        // determine whether requests tab or deliveries
        TransactionPanel panel = null;
        if (sel instanceof JTabbedPane) {
            JTabbedPane tabs = (JTabbedPane) sel;
            Component comp = tabs.getSelectedComponent();
            if (comp instanceof TransactionPanel) panel = (TransactionPanel) comp;
        } else if (sel instanceof TransactionPanel) {
            panel = (TransactionPanel) sel;
        }

        if (panel == null) {
            JOptionPane.showMessageDialog(this, "No transaction panel selected.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //transactionId
        String txId = panel.getSelectedTransactionId();
        if (txId == null) {
            JOptionPane.showMessageDialog(this, "No transaction selected.", "Info", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //get the items
        List<Transaction> items = panel.getTransactionsForSelectedId();
        if (items.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "No items found for selected transaction.", "Info", javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        //ensure receipts directory
        File receiptsDir = new File("data/Receipts");
        if (!receiptsDir.exists()) receiptsDir.mkdirs();

        //set the file name
        String source = panel.getSourceName();
        //build filename: <TXID>_<source>.txt (sanitize spaces)
        String fileName = txId + "_" + source.replaceAll("\\s+", "_") + ".txt";
        File out = new File(receiptsDir, fileName);

        //write the details in the receipt txt file
        try (BufferedWriter bw = new BufferedWriter(new FileWriter(out))) {
            if (panel.getTransactionType() == TransactionType.DELIVERY) {
                // delivery receipt header
                bw.write("Delivery Receipt\n");
                bw.write("Delivery ID: " + txId + "\n");
                bw.write("Supplier: " + source + "\n");
                bw.write("Date Created: " + (items.get(0).getDateCreated()==null?"":items.get(0).getDateCreated().toString()) + "\n");
                bw.write("------------------------------------------------------------\n");
                
                //write the items
                bw.write(String.format("%-12s %-30s %-8s %-8s %-12s\n","Item Code","Item Name","Quantity","Unit","Date Completed"));
                for (Transaction t : items) {
                    bw.write(String.format("%-12s %-30s %-8d %-8s %-12s\n",
                        t.getItemCode(), 
                        t.getItemName(), 
                        t.getQuantity(), 
                        t.getUnit(), 
                        (t.getDateCompleted()==null?"":t.getDateCompleted().toString())));
                }
                bw.newLine();
                bw.newLine();   
                bw.write("Delivered By: " + (items.get(0).getReleasedOrDeliveredBy()));
                bw.newLine();
                bw.newLine();
                bw.newLine();
                bw.write("Received By: " + (items.get(0).getUserName()));
            } else {
                // request receipt header
                bw.write("Request Receipt\n");
                bw.write("Request ID: " + txId + "\n");
                bw.write("Department: " + source + "\n");
                bw.write("Date Created: " + (items.get(0).getDateCreated()==null?"":items.get(0).getDateCreated().toString()) + "\n");
                bw.write("------------------------------------------------------------\n");
                
                //write the items
                bw.write(String.format("%-12s %-30s %-8s %-12s %-8s %-20s %-25s %-12s\n",
                    "Item Code","Item Name","Quantity","To Release","Unit","Status", "Date Approved/Rejected","Date Completed"));
                for (Transaction t : items) {
                    bw.write(String.format("%-12s %-30s %-8d %-12d %-8s %-20s %-25s %-12s\n",
                        t.getItemCode(), 
                        t.getItemName(), 
                        t.getQuantity(),
                        t.getQuantityToBeReleased(), 
                        t.getUnit(), 
                        (t.getStatus()==null?"":t.getStatus()), 
                        (t.getDateApproved()==null?"":t.getDateApproved().toString()),
                        (t.getDateCompleted()==null?"":t.getDateCompleted().toString())));
                }
                bw.newLine();
                bw.newLine();   
                bw.write("Requested By: " + (items.get(0).getUserName()));
                bw.newLine();
                bw.newLine();
                bw.newLine();
                bw.write("Released By: " + (items.get(0).getReleasedOrDeliveredBy()));
            }
            bw.flush();
        }

        JOptionPane.showMessageDialog(this, "Receipt saved to: " + out.getAbsolutePath(), "Saved", JOptionPane.INFORMATION_MESSAGE);
    }

    //setup the request tabs
    private void setupRequestTabs(List<Transaction> allTransactions) throws IOException {
        requestsTabbedPane = new JTabbedPane();

        //get the dept transactions
        for (String dept : transactionManager.getDeptFiles().keySet()) {
            List<Transaction> deptTransactions = allTransactions.stream()
                .filter(t -> t.getType() == TransactionType.REQUEST)
                .filter(t -> t.getSource().equals(dept))
                .toList();

            TransactionPanel panel = new TransactionPanel(deptTransactions, TransactionType.REQUEST, dept);
            requestsTabbedPane.addTab(dept, panel);
        }
        if(transactionsTabbedPane.getTabCount() > 0) { transactionsTabbedPane.remove(0);}
        transactionsTabbedPane.addTab("Requests", requestsTabbedPane);
    }

    //setup the delivery tab
    private void setupDeliveryTab(List<Transaction> allTransactions) throws IOException {
        // List<Transaction> deliveryTransactions = allTransactions.stream()
        //     .filter(t -> t.getType() == TransactionType.DELIVERY)
        //     .toList();

        // //group deliveries by supplier so each supplier has its own tab and TransactionPanel
        // JTabbedPane deliveryTabbedPane = new JTabbedPane();
        // Map<String, List<Transaction>> bySupplier = new LinkedHashMap<>();
        // for (Transaction t : deliveryTransactions) {
        //     String supplier = t.getSource() == null ? "Unknown" : t.getSource();
        //     bySupplier.computeIfAbsent(supplier, k -> new ArrayList<>()).add(t);
        // }

        // for (Map.Entry<String, java.util.List<Transaction>> e : bySupplier.entrySet()) {
        //     String supplier = e.getKey();
        //     List<Transaction> list = e.getValue();
        //     TransactionPanel panel = new TransactionPanel(list, TransactionType.DELIVERY, supplier);
        //     deliveryTabbedPane.addTab(supplier, panel);
        // }

        // if (transactionsTabbedPane.getTabCount() > 1) {
        //     // replace any placeholder tab after requests
        //     // find index of "Deliveries" tab if exists
        // }

        // transactionsTabbedPane.addTab("Deliveries", deliveryTabbedPane);

        List<Transaction> deliveryTransactions = allTransactions.stream()
            .filter(t -> t.getType() == TransactionType.DELIVERY)
            .toList();
        
        // Remove existing Deliveries tab if present
        for (int i = 0; i < transactionsTabbedPane.getTabCount(); i++) {
            if ("Deliveries".equals(transactionsTabbedPane.getTitleAt(i))) {
                transactionsTabbedPane.remove(i);
                break;
            }
        }

        // If no deliveries, show a message panel instead
        if (deliveryTransactions.isEmpty()) {
            JPanel emptyPanel = new JPanel(new BorderLayout());
            emptyPanel.add(new JLabel("No delivery records found.", JLabel.CENTER),
                        BorderLayout.CENTER);
            transactionsTabbedPane.addTab("Deliveries", emptyPanel);
            return;
        }

        // Group deliveries by supplier
        Map<String, List<Transaction>> bySupplier = new LinkedHashMap<>();
        for (Transaction t : deliveryTransactions) {
            String supplier = (t.getSource() == null || t.getSource().isBlank())
                    ? "Unknown"
                    : t.getSource();

            bySupplier.computeIfAbsent(supplier, k -> new ArrayList<>()).add(t);
        }

        // Create nested tabbed pane
        JTabbedPane deliveryTabbedPane = new JTabbedPane();

        for (Map.Entry<String, List<Transaction>> entry : bySupplier.entrySet()) {
            String supplier = entry.getKey();
            List<Transaction> list = entry.getValue();

            TransactionPanel panel =
                new TransactionPanel(list, TransactionType.DELIVERY, supplier);

            deliveryTabbedPane.addTab(supplier, panel);
        }

        transactionsTabbedPane.addTab("Deliveries", deliveryTabbedPane);

        // VERY IMPORTANT
        transactionsTabbedPane.revalidate();
        transactionsTabbedPane.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel deliveriesLbl;
    private javax.swing.JLabel homeLbl;
    private javax.swing.JLabel inventoryLbl;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel logoutLbl;
    private javax.swing.JLabel requestsLbl;
    private javax.swing.JTabbedPane requestsTabbedPane;
    private javax.swing.JButton saveReceiptBtn;
    private javax.swing.JButton saveReportBtn;
    private javax.swing.JLabel transactionsLbl;
    private javax.swing.JPanel transactionsPnl;
    private javax.swing.JTabbedPane transactionsTabbedPane;
    // End of variables declaration//GEN-END:variables
}
